--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_gucefIMAGE_TestApp" )

  platforms( { "ALL", "LINUX32", "LINUX64", "WIN32", "WIN64" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "tests/gucefIMAGE_TestApp" )

filter "LINUX32"
  include( "dependencies/DevIL/DevIL" )
  include( "dependencies/FreeImage" )
  include( "dependencies/Little-CMS" )
  include( "dependencies/flic" )
  include( "dependencies/jasper/src/libjasper" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libjpeg" )
  include( "dependencies/libmng" )
  include( "dependencies/libparsifal" )
  include( "dependencies/libpng" )
  include( "dependencies/libsquish" )
  include( "dependencies/openexr" )
  include( "dependencies/tiff/libtiff" )
  include( "dependencies/zlib" )
  include( "platform/gucefCORE" )
  include( "platform/gucefIMAGE" )
  include( "platform/gucefMT" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/IMAGE/imgpluginDEVIL" )
  include( "plugins/IMAGE/imgpluginFLIC" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/IMAGE/imgpluginITV" )
  include( "tests/gucefIMAGE_TestApp" )

filter "LINUX64"
  include( "dependencies/DevIL/DevIL" )
  include( "dependencies/FreeImage" )
  include( "dependencies/Little-CMS" )
  include( "dependencies/flic" )
  include( "dependencies/jasper/src/libjasper" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libjpeg" )
  include( "dependencies/libmng" )
  include( "dependencies/libparsifal" )
  include( "dependencies/libpng" )
  include( "dependencies/libsquish" )
  include( "dependencies/openexr" )
  include( "dependencies/tiff/libtiff" )
  include( "dependencies/zlib" )
  include( "platform/gucefCORE" )
  include( "platform/gucefIMAGE" )
  include( "platform/gucefMT" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/IMAGE/imgpluginDEVIL" )
  include( "plugins/IMAGE/imgpluginFLIC" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/IMAGE/imgpluginITV" )
  include( "tests/gucefIMAGE_TestApp" )

filter "WIN32"
  include( "dependencies/DevIL/DevIL" )
  include( "dependencies/FreeImage" )
  include( "dependencies/Little-CMS" )
  include( "dependencies/flic" )
  include( "dependencies/jasper/src/libjasper" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libjpeg" )
  include( "dependencies/libmng" )
  include( "dependencies/libparsifal" )
  include( "dependencies/libpng" )
  include( "dependencies/libsquish" )
  include( "dependencies/openexr" )
  include( "dependencies/tiff/libtiff" )
  include( "dependencies/zlib" )
  include( "platform/gucefCORE" )
  include( "platform/gucefIMAGE" )
  include( "platform/gucefMT" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/IMAGE/imgpluginDEVIL" )
  include( "plugins/IMAGE/imgpluginFLIC" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/IMAGE/imgpluginITV" )
  include( "tests/gucefIMAGE_TestApp" )

filter "WIN64"
  include( "dependencies/DevIL/DevIL" )
  include( "dependencies/FreeImage" )
  include( "dependencies/Little-CMS" )
  include( "dependencies/flic" )
  include( "dependencies/jasper/src/libjasper" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libjpeg" )
  include( "dependencies/libmng" )
  include( "dependencies/libparsifal" )
  include( "dependencies/libpng" )
  include( "dependencies/libsquish" )
  include( "dependencies/openexr" )
  include( "dependencies/tiff/libtiff" )
  include( "dependencies/zlib" )
  include( "platform/gucefCORE" )
  include( "platform/gucefIMAGE" )
  include( "platform/gucefMT" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/IMAGE/imgpluginDEVIL" )
  include( "plugins/IMAGE/imgpluginFLIC" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/IMAGE/imgpluginITV" )
  include( "tests/gucefIMAGE_TestApp" )
