#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := ProjectGen
LOCAL_MODULE_FILENAME := libProjectGen
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/gucefProjectGen_CAndroidMakefileGenerator.cpp \
  src/gucefProjectGen_CArduinoCLIGenerator.cpp \
  src/gucefProjectGen_CCIHelperGenerator.cpp \
  src/gucefProjectGen_CCMakeProjectGenerator.cpp \
  src/gucefProjectGen_CDirCrawlingProjectInfoGatherer.cpp \
  src/gucefProjectGen_CDirPreprocessorManager.cpp \
  src/gucefProjectGen_CIDirPreprocessor.cpp \
  src/gucefProjectGen_CIProjectGenerator.cpp \
  src/gucefProjectGen_CIProjectInfoGatherer.cpp \
  src/gucefProjectGen_CIProjectPreprocessor.cpp \
  src/gucefProjectGen_CPremake4ProjectGenerator.cpp \
  src/gucefProjectGen_CPremake5ProjectGenerator.cpp \
  src/gucefProjectGen_CProjectGenGlobal.cpp \
  src/gucefProjectGen_CProjectPreprocessorManager.cpp \
  src/gucefProjectGen_CXmlProjectGenerator.cpp \
  src/gucefProjectGen_DataTypes.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../../common/include \
  $(MY_MODULE_PATH)/../../platform/gucefCORE/include \
  $(MY_MODULE_PATH)/../../platform/gucefCORE/include/android \
  $(MY_MODULE_PATH)/../../platform/gucefCORE/include/c_api \
  $(MY_MODULE_PATH)/../../platform/gucefMT/include

LOCAL_CFLAGS := -DGUCEF_PROJECTGEN_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

