--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: zookeeper


project( "zookeeper" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )



configuration( {} )
kind( "StaticLib" )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "generated/zookeeper.jute.h",
  "include/proto.h",
  "include/recordio.h",
  "include/winconfig.h",
  "include/zookeeper.h",
  "include/zookeeper_log.h",
  "include/zookeeper_version.h",
  "src/addrvec.h",
  "src/winport.h",
  "src/zk_adaptor.h",
  "src/zk_hashtable.h",
  "src/hashtable/hashtable.h",
  "src/hashtable/hashtable_itr.h",
  "src/hashtable/hashtable_private.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "generated/zookeeper.jute.c",
  "src/addrvec.c",
  "src/cli.c",
  "src/load_gen.c",
  "src/mt_adaptor.c",
  "src/recordio.c",
  "src/st_adaptor.c",
  "src/winport.c",
  "src/zk_hashtable.c",
  "src/zk_log.c",
  "src/zookeeper.c",
  "src/hashtable/hashtable.c",
  "src/hashtable/hashtable_itr.c"
 } )


configuration( {} )
includedirs( { "generated", "include", "src", "src/hashtable" } )
