--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: guidriverRocket


project( "guidriverRocket" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "RocketControls", "RocketCore", "gucefCORE", "gucefGUI", "gucefINPUT", "gucefMT", "gucefVFS" } )
links( { "RocketControls", "RocketCore", "gucefCORE", "gucefGUI", "gucefINPUT", "gucefMT", "gucefVFS" } )


configuration( {} )
defines( { "GUCEF_GUIDRIVERROCKET_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/guidriverRocket.h",
  "include/guidriverRocket_CButtonImp.h",
  "include/guidriverRocket_CCheckboxImp.h",
  "include/guidriverRocket_CComboboxImp.h",
  "include/guidriverRocket_CDataManager.h",
  "include/guidriverRocket_CEditboxImp.h",
  "include/guidriverRocket_CFileOpenDialogImp.h",
  "include/guidriverRocket_CFileSaveDialogImp.h",
  "include/guidriverRocket_CFileSystemDialogImp.h",
  "include/guidriverRocket_CFormBackendImp.h",
  "include/guidriverRocket_CGUIContext.h",
  "include/guidriverRocket_CGridViewImp.h",
  "include/guidriverRocket_CImageFrameImp.h",
  "include/guidriverRocket_CInputAdapter.h",
  "include/guidriverRocket_CLabelImp.h",
  "include/guidriverRocket_CListBoxImp.h",
  "include/guidriverRocket_CMemoboxImp.h",
  "include/guidriverRocket_CMenuBarImp.h",
  "include/guidriverRocket_CPopupMenuImp.h",
  "include/guidriverRocket_CProgressBarImp.h",
  "include/guidriverRocket_CPushButtonImp.h",
  "include/guidriverRocket_CRenderContextImp.h",
  "include/guidriverRocket_CRocketStreamAdapter.h",
  "include/guidriverRocket_CRocketSystemInterface.h",
  "include/guidriverRocket_CRocketVFSInterface.h",
  "include/guidriverRocket_CSpinnerImp.h",
  "include/guidriverRocket_CTabContentPaneImp.h",
  "include/guidriverRocket_CTabControlImp.h",
  "include/guidriverRocket_CTreeviewImp.h",
  "include/guidriverRocket_CVFSInfoProvider.h",
  "include/guidriverRocket_CWidgetImp.h",
  "include/guidriverRocket_CWindowImp.h",
  "include/guidriverRocket_ETypes.h",
  "include/guidriverRocket_config.h",
  "include/guidriverRocket_macros.h",
  "include/guidriverRocket_pluginAPI.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/guidriverRocket.cpp",
  "src/guidriverRocket_CButtonImp.cpp",
  "src/guidriverRocket_CCheckboxImp.cpp",
  "src/guidriverRocket_CComboboxImp.cpp",
  "src/guidriverRocket_CDataManager.cpp",
  "src/guidriverRocket_CEditboxImp.cpp",
  "src/guidriverRocket_CFileOpenDialogImp.cpp",
  "src/guidriverRocket_CFileSaveDialogImp.cpp",
  "src/guidriverRocket_CFileSystemDialogImp.cpp",
  "src/guidriverRocket_CFormBackendImp.cpp",
  "src/guidriverRocket_CGUIContext.cpp",
  "src/guidriverRocket_CGridViewImp.cpp",
  "src/guidriverRocket_CIOAccessToRocketStreamAdapter.cpp",
  "src/guidriverRocket_CImageFrameImp.cpp",
  "src/guidriverRocket_CInputAdapter.cpp",
  "src/guidriverRocket_CLabelImp.cpp",
  "src/guidriverRocket_CListboxImp.cpp",
  "src/guidriverRocket_CMemoboxImp.cpp",
  "src/guidriverRocket_CMenuBarImp.cpp",
  "src/guidriverRocket_CPopupMenuImp.cpp",
  "src/guidriverRocket_CProgressBarImp.cpp",
  "src/guidriverRocket_CPushButtonImp.cpp",
  "src/guidriverRocket_CRenderContextImp.cpp",
  "src/guidriverRocket_CRocketInputAdapter.cpp",
  "src/guidriverRocket_CRocketStreamAdapter.cpp",
  "src/guidriverRocket_CRocketSystemInterface.cpp",
  "src/guidriverRocket_CRocketVFSInterface.cpp",
  "src/guidriverRocket_CSpinnerImp.cpp",
  "src/guidriverRocket_CTabContentPaneImp.cpp",
  "src/guidriverRocket_CTabControlImp.cpp",
  "src/guidriverRocket_CTreeviewImp.cpp",
  "src/guidriverRocket_CVFSInfoProvider.cpp",
  "src/guidriverRocket_CWidgetImp.cpp",
  "src/guidriverRocket_CWindowImp.cpp",
  "src/guidriverRocket_pluginAPI.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/freetype/include", "../../../dependencies/freetype/include/freetype", "../../../dependencies/freetype/include/freetype/config", "../../../dependencies/freetype/include/freetype/internal", "../../../dependencies/freetype/include/freetype/internal/services", "../../../dependencies/freetype/src", "../../../dependencies/freetype/src/winfonts", "../../../dependencies/libRocket/Include", "../../../dependencies/libRocket/Include/Rocket", "../../../dependencies/libRocket/Include/Rocket/Controls", "../../../dependencies/libRocket/Include/Rocket/Core", "../../../dependencies/libRocket/Include/Rocket/Core/Python", "../../../dependencies/libRocket/Include/Rocket/Debugger", "../../../dependencies/libRocket/Source/Controls", "../../../dependencies/libRocket/Source/Core", "../../../platform/gucefCORE/include", "../../../platform/gucefGUI/include", "../../../platform/gucefIMAGE/include", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include", "../../../platform/gucefVFS/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
