#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := CEGUI.WindowRendererSets.Core
LOCAL_MODULE_FILENAME := libCEGUI.WindowRendererSets.Core
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  Button.cpp \
  Default.cpp \
  Editbox.cpp \
  FrameWindow.cpp \
  ItemEntry.cpp \
  ItemListbox.cpp \
  ListHeader.cpp \
  ListHeaderSegment.cpp \
  Listbox.cpp \
  MenuItem.cpp \
  Menubar.cpp \
  Module.cpp \
  MultiColumnList.cpp \
  MultiLineEditbox.cpp \
  PopupMenu.cpp \
  ProgressBar.cpp \
  ScrollablePane.cpp \
  Scrollbar.cpp \
  Slider.cpp \
  Static.cpp \
  StaticImage.cpp \
  StaticText.cpp \
  TabButton.cpp \
  TabControl.cpp \
  Titlebar.cpp \
  ToggleButton.cpp \
  Tooltip.cpp \
  Tree.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/../../../include

LOCAL_CFLAGS := -DCEGUICOREWINDOWRENDERERSET_EXPORTS


LOCAL_SHARED_LIBRARIES := \
  CEGUI

include $(BUILD_SHARED_LIBRARY)

