--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: CEGUI.WindowRendererSets.Core


project( "CEGUI.WindowRendererSets.Core" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "CEGUI" } )
links( { "CEGUI" } )


configuration( {} )
defines( { "CEGUICOREWINDOWRENDERERSET_EXPORTS" } )


configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "Button.cpp",
  "Default.cpp",
  "Editbox.cpp",
  "FrameWindow.cpp",
  "ItemEntry.cpp",
  "ItemListbox.cpp",
  "ListHeader.cpp",
  "ListHeaderSegment.cpp",
  "Listbox.cpp",
  "MenuItem.cpp",
  "Menubar.cpp",
  "Module.cpp",
  "MultiColumnList.cpp",
  "MultiLineEditbox.cpp",
  "PopupMenu.cpp",
  "ProgressBar.cpp",
  "ScrollablePane.cpp",
  "Scrollbar.cpp",
  "Slider.cpp",
  "Static.cpp",
  "StaticImage.cpp",
  "StaticText.cpp",
  "TabButton.cpp",
  "TabControl.cpp",
  "Titlebar.cpp",
  "ToggleButton.cpp",
  "Tooltip.cpp",
  "Tree.cpp"
 } )


configuration( {} )
includedirs( { "../../../include" } )
