--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefGUI_TestApp


configuration( { "ANDROID" } )
  project( "gucefGUI_TestApp" )

configuration( { "LINUX32" } )
  project( "gucefGUI_TestApp" )

configuration( { "LINUX64" } )
  project( "gucefGUI_TestApp" )

configuration( { "WIN32" } )
  project( "gucefGUI_TestApp" )

configuration( { "WIN64" } )
  project( "gucefGUI_TestApp" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "ANDROID" } )
language( "C++" )

configuration( { "LINUX32" } )
language( "C++" )

configuration( { "LINUX64" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "ANDROID" } )


configuration( { ANDROID } )
kind( "ConsoleApp" )
configuration( { "LINUX32" } )


configuration( { LINUX32 } )
kind( "ConsoleApp" )
configuration( { "LINUX64" } )


configuration( { LINUX64 } )
kind( "ConsoleApp" )
configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "WindowedApp" )
  
configuration( { ANDROID } )
links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  

configuration( { ANDROID } )
defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )
  
configuration( { LINUX32 } )
links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  

configuration( { LINUX32 } )
defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )
  
configuration( { LINUX64 } )
links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  

configuration( { LINUX64 } )
defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )
  
configuration( { WIN32 } )
links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )
  
configuration( { WIN64 } )
links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )


configuration( { "ANDROID" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "LINUX32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCORE/include", "../../platform/gucefGUI/include", "../../platform/gucefIMAGE/include", "../../platform/gucefINPUT/include", "../../platform/gucefMT/include", "../../platform/gucefVFS/include" } )

configuration( { "ANDROID" } )
includedirs( { "../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )
