CALL CMakeCommon.bat

ECHO *** Set MVC14 specifics and run CMake ***

SET MVC14_OUTPUTDIR="%OUTPUTDIR%\MVC14Nsight"
CMake.exe -DCMAKE_SYSTEM_NAME=Android -DBUILD_SHARED_LIBS=ON -G"Visual Studio 14 2015" -H"%SRCROOTDIR%" -B%MVC14_OUTPUTDIR%
PAUSE