--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: inputdriverOIS


configuration( { "LINUX32" } )
  project( "inputdriverOIS" )

configuration( { "LINUX64" } )
  project( "inputdriverOIS" )

configuration( { "WIN32" } )
  project( "inputdriverOIS" )

configuration( { "WIN64" } )
  project( "inputdriverOIS" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX32" } )
language( "C++" )

configuration( { "LINUX64" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "LINUX32" } )


configuration( { LINUX32 } )
kind( "SharedLib" )
configuration( { "LINUX64" } )


configuration( { LINUX64 } )
kind( "SharedLib" )
configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )
  
configuration( { LINUX32 } )
links( { "OIS", "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "OIS" } )
  

configuration( { LINUX32 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVEROIS_BUILD_MODULE" } )
  
configuration( { LINUX64 } )
links( { "OIS", "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "OIS" } )
  

configuration( { LINUX64 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVEROIS_BUILD_MODULE" } )
  
configuration( { WIN32 } )
links( { "OIS", "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "OIS" } )
  

configuration( { WIN32 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVEROIS_BUILD_MODULE" } )
  
configuration( { WIN64 } )
links( { "OIS", "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "OIS" } )
  

configuration( { WIN64 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVEROIS_BUILD_MODULE" } )


configuration( { "LINUX32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DLLMainInputDriverOIS.h",
      "include/gucefINPUT_OISJoystickListener.h",
      "include/gucefINPUT_OISKeyboardListener.h",
      "include/gucefINPUT_OISMouseListener.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/DLLMainInputDriverOIS.cpp",
      "src/gucefINPUT_OISJoystickListener.cpp",
      "src/gucefINPUT_OISKeyboardListener.cpp",
      "src/gucefINPUT_OISMouseListener.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DLLMainInputDriverOIS.h",
      "include/gucefINPUT_OISJoystickListener.h",
      "include/gucefINPUT_OISKeyboardListener.h",
      "include/gucefINPUT_OISMouseListener.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/DLLMainInputDriverOIS.cpp",
      "src/gucefINPUT_OISJoystickListener.cpp",
      "src/gucefINPUT_OISKeyboardListener.cpp",
      "src/gucefINPUT_OISMouseListener.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DLLMainInputDriverOIS.h",
      "include/gucefINPUT_OISJoystickListener.h",
      "include/gucefINPUT_OISKeyboardListener.h",
      "include/gucefINPUT_OISMouseListener.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/DLLMainInputDriverOIS.cpp",
      "src/gucefINPUT_OISJoystickListener.cpp",
      "src/gucefINPUT_OISKeyboardListener.cpp",
      "src/gucefINPUT_OISMouseListener.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DLLMainInputDriverOIS.h",
      "include/gucefINPUT_OISJoystickListener.h",
      "include/gucefINPUT_OISKeyboardListener.h",
      "include/gucefINPUT_OISMouseListener.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/DLLMainInputDriverOIS.cpp",
      "src/gucefINPUT_OISJoystickListener.cpp",
      "src/gucefINPUT_OISKeyboardListener.cpp",
      "src/gucefINPUT_OISMouseListener.cpp"
    } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/OIS/includes", "../../../dependencies/OIS/includes/linux", "../../../dependencies/OIS/src/extras/LIRC", "../../../platform/gucefCORE/include/linux", "include" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/OIS/includes", "../../../dependencies/OIS/includes/linux", "../../../dependencies/OIS/src/extras/LIRC", "../../../platform/gucefCORE/include/linux", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/OIS/#$#ENVVAR:DXSDK_DIR#$#/Include", "../../../dependencies/OIS/includes", "../../../dependencies/OIS/includes/win32", "../../../dependencies/OIS/src/extras/LIRC", "../../../dependencies/OIS/src/win32/extras/WiiMote", "../../../dependencies/external", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/OIS/includes", "../../../dependencies/OIS/src/extras/LIRC", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin", "include" } )
