#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := lcms2
LOCAL_MODULE_FILENAME := liblcms2
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/cmsalpha.c \
  src/cmscam02.c \
  src/cmscgats.c \
  src/cmscnvrt.c \
  src/cmserr.c \
  src/cmsgamma.c \
  src/cmsgmt.c \
  src/cmshalf.c \
  src/cmsintrp.c \
  src/cmsio0.c \
  src/cmsio1.c \
  src/cmslut.c \
  src/cmsmd5.c \
  src/cmsmtrx.c \
  src/cmsnamed.c \
  src/cmsopt.c \
  src/cmspack.c \
  src/cmspcs.c \
  src/cmsplugin.c \
  src/cmsps2.c \
  src/cmssamp.c \
  src/cmssm.c \
  src/cmstypes.c \
  src/cmsvirt.c \
  src/cmswtpnt.c \
  src/cmsxform.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/src

LOCAL_CFLAGS := -DCMS_DLL_BUILD

include $(BUILD_SHARED_LIBRARY)

