--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MyGUI.OgrePlatform


configuration( { "LINUX32" } )
  project( "MyGUI.OgrePlatform" )

configuration( { "LINUX64" } )
  project( "MyGUI.OgrePlatform" )

configuration( { "WIN32" } )
  project( "MyGUI.OgrePlatform" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX32" } )
language( "C++" )

configuration( { "LINUX64" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "LINUX32" } )


configuration( { LINUX32 } )
kind( "SharedLib" )
configuration( { "LINUX64" } )


configuration( { LINUX64 } )
kind( "SharedLib" )
configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
  
configuration( { LINUX32 } )
links( { "MyGUI.Engine", "Ogre" } )
  links( { "MyGUI.Engine", "Ogre" } )
  
configuration( { LINUX64 } )
links( { "MyGUI.Engine", "Ogre" } )
  links( { "MyGUI.Engine", "Ogre" } )
  
configuration( { WIN32 } )
links( { "MyGUI.Engine", "Ogre" } )
  links( { "MyGUI.Engine", "Ogre" } )


configuration( { "LINUX32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../../Common/FileSystemInfo/FileSystemInfo.h",
      "include/MyGUI_LastHeader.h",
      "include/MyGUI_OgreDataManager.h",
      "include/MyGUI_OgreDataStream.h",
      "include/MyGUI_OgreDiagnostic.h",
      "include/MyGUI_OgrePlatform.h",
      "include/MyGUI_OgreRTTexture.h",
      "include/MyGUI_OgreRenderManager.h",
      "include/MyGUI_OgreTexture.h",
      "include/MyGUI_OgreVertexBuffer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MyGUI_OgreDataManager.cpp",
      "src/MyGUI_OgreDataStream.cpp",
      "src/MyGUI_OgreRTTexture.cpp",
      "src/MyGUI_OgreRenderManager.cpp",
      "src/MyGUI_OgreTexture.cpp",
      "src/MyGUI_OgreVertexBuffer.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../../Common/FileSystemInfo/FileSystemInfo.h",
      "include/MyGUI_LastHeader.h",
      "include/MyGUI_OgreDataManager.h",
      "include/MyGUI_OgreDataStream.h",
      "include/MyGUI_OgreDiagnostic.h",
      "include/MyGUI_OgrePlatform.h",
      "include/MyGUI_OgreRTTexture.h",
      "include/MyGUI_OgreRenderManager.h",
      "include/MyGUI_OgreTexture.h",
      "include/MyGUI_OgreVertexBuffer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MyGUI_OgreDataManager.cpp",
      "src/MyGUI_OgreDataStream.cpp",
      "src/MyGUI_OgreRTTexture.cpp",
      "src/MyGUI_OgreRenderManager.cpp",
      "src/MyGUI_OgreTexture.cpp",
      "src/MyGUI_OgreVertexBuffer.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../../Common/FileSystemInfo/FileSystemInfo.h",
      "include/MyGUI_LastHeader.h",
      "include/MyGUI_OgreDataManager.h",
      "include/MyGUI_OgreDataStream.h",
      "include/MyGUI_OgreDiagnostic.h",
      "include/MyGUI_OgrePlatform.h",
      "include/MyGUI_OgreRTTexture.h",
      "include/MyGUI_OgreRenderManager.h",
      "include/MyGUI_OgreTexture.h",
      "include/MyGUI_OgreVertexBuffer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MyGUI_OgreDataManager.cpp",
      "src/MyGUI_OgreDataStream.cpp",
      "src/MyGUI_OgreRTTexture.cpp",
      "src/MyGUI_OgreRenderManager.cpp",
      "src/MyGUI_OgreTexture.cpp",
      "src/MyGUI_OgreVertexBuffer.cpp"
    } )


configuration( {} )
includedirs( { "../../../../Ogre/OgreMain/include", "../../../../Ogre/OgreMain/include/Hash", "../../../../Ogre/OgreMain/include/Threading", "../../../../Ogre/OgreMain/src", "../../../../Ogre/OgreMain/src/nedmalloc", "../../../../Ogre/OgreMain/src/stbi", "../../../../Ogre/include", "../../../../freetype/include", "../../../../freetype/include/freetype", "../../../../freetype/include/freetype/config", "../../../../freetype/include/freetype/internal", "../../../../freetype/include/freetype/internal/services", "../../../../freetype/src", "../../../../freetype/src/winfonts", "../../../MyGUIEngine/include" } )

configuration( { "LINUX32" } )
includedirs( { "../../../Common/FileSystemInfo", "include" } )

configuration( { "LINUX64" } )
includedirs( { "../../../Common/FileSystemInfo", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../../../Ogre/OgreMain/include/WIN32", "../../../../Ogre/OgreMain/src/WIN32", "../../../Common/FileSystemInfo", "include" } )
