@echo off
SET GUCEF_THEBATCHDIR=%~dp0

echo #-------------------------------------------------------------------
echo # This file has been automatically generated by ProjectGenerator    
echo # which is part of a build system designed for GUCEF                
echo #     (Galaxy Unlimited Framework)                                  
echo # For the latest info, see http://www.VanvelzenSoftware.com/        
echo #                                                                   
echo # The contents of this file are placed in the public domain. Feel   
echo # free to make use of it in any way you like.                       
echo #-------------------------------------------------------------------


call .\gucefHeaders_create_symlinks.bat
call .\gucefCOM_create_symlinks.bat
call .\gucefCOMCORE_create_symlinks.bat
call .\gucefCORE_create_symlinks.bat
call .\gucefDRN_create_symlinks.bat
call .\gucefGUI_create_symlinks.bat
call .\gucefIMAGE_create_symlinks.bat
call .\gucefINPUT_create_symlinks.bat
call .\gucefKAITAI_create_symlinks.bat
call .\gucefLOADER_create_symlinks.bat
call .\gucefMATH_create_symlinks.bat
call .\gucefMT_create_symlinks.bat
call .\gucefMULTIPLAY_create_symlinks.bat
call .\gucefPATCHER_create_symlinks.bat
call .\gucefPRODMAN_create_symlinks.bat
call .\gucefPUBSUB_create_symlinks.bat
call .\gucefSMDRN_create_symlinks.bat
call .\gucefVFS_create_symlinks.bat
call .\gucefWEB_create_symlinks.bat
