--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: inputdriverXWINMSG


configuration( { "LINUX" } )
  project( "inputdriverXWINMSG" )
location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX" } )
language( "C++" )

configuration( { "LINUX" } )


configuration( { LINUX } )
kind( "SharedLib" )

configuration( { "LINUX" } )
  
configuration( { LINUX } )
links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  

configuration( { LINUX } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVERXWINMSG_BUILD_MODULE" } )


configuration( { "LINUX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/inputdriverXWINMSG.h",
      "include/inputdriverXWINMSG_CEventListner.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/inputdriverXWINMSG.cpp",
      "src/inputdriverXWINMSG_CEventListner.cpp"
    } )


configuration( {} )
includedirs( { "../../../common/include", "../../../gucefCORE/include", "../../../gucefINPUT/include", "../../../gucefMT/include" } )

configuration( { "LINUX" } )
includedirs( { "../../../gucefCORE/include/linux", "include" } )
