#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := RdKafka
LOCAL_MODULE_FILENAME := libRdKafka
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/cJSON.c \
  src/crc32c.c \
  src/lz4.c \
  src/lz4frame.c \
  src/lz4hc.c \
  src/rdaddr.c \
  src/rdavl.c \
  src/rdbase64.c \
  src/rdbuf.c \
  src/rdcrc32.c \
  src/rddl.c \
  src/rdfnv1a.c \
  src/rdgz.c \
  src/rdhdrhistogram.c \
  src/rdkafka.c \
  src/rdkafka_admin.c \
  src/rdkafka_assignment.c \
  src/rdkafka_assignor.c \
  src/rdkafka_aux.c \
  src/rdkafka_background.c \
  src/rdkafka_broker.c \
  src/rdkafka_buf.c \
  src/rdkafka_cert.c \
  src/rdkafka_cgrp.c \
  src/rdkafka_conf.c \
  src/rdkafka_coord.c \
  src/rdkafka_error.c \
  src/rdkafka_event.c \
  src/rdkafka_feature.c \
  src/rdkafka_fetcher.c \
  src/rdkafka_header.c \
  src/rdkafka_idempotence.c \
  src/rdkafka_interceptor.c \
  src/rdkafka_lz4.c \
  src/rdkafka_metadata.c \
  src/rdkafka_metadata_cache.c \
  src/rdkafka_mock.c \
  src/rdkafka_mock_cgrp.c \
  src/rdkafka_mock_handlers.c \
  src/rdkafka_msg.c \
  src/rdkafka_msgset_reader.c \
  src/rdkafka_msgset_writer.c \
  src/rdkafka_offset.c \
  src/rdkafka_op.c \
  src/rdkafka_partition.c \
  src/rdkafka_pattern.c \
  src/rdkafka_plugin.c \
  src/rdkafka_queue.c \
  src/rdkafka_range_assignor.c \
  src/rdkafka_request.c \
  src/rdkafka_roundrobin_assignor.c \
  src/rdkafka_sasl.c \
  src/rdkafka_sasl_plain.c \
  src/rdkafka_sticky_assignor.c \
  src/rdkafka_subscription.c \
  src/rdkafka_timer.c \
  src/rdkafka_topic.c \
  src/rdkafka_transport.c \
  src/rdkafka_txnmgr.c \
  src/rdlist.c \
  src/rdlog.c \
  src/rdmap.c \
  src/rdmurmur2.c \
  src/rdports.c \
  src/rdrand.c \
  src/rdregex.c \
  src/rdstring.c \
  src/rdunittest.c \
  src/rdvarint.c \
  src/rdxxhash.c \
  src/regexp.c \
  src/snappy.c \
  src/tinycthread.c \
  src/tinycthread_extra.c \
  src-cpp/ConfImpl.cpp \
  src-cpp/ConsumerImpl.cpp \
  src-cpp/HandleImpl.cpp \
  src-cpp/HeadersImpl.cpp \
  src-cpp/KafkaConsumerImpl.cpp \
  src-cpp/MessageImpl.cpp \
  src-cpp/MetadataImpl.cpp \
  src-cpp/ProducerImpl.cpp \
  src-cpp/QueueImpl.cpp \
  src-cpp/RdKafka.cpp \
  src-cpp/TopicImpl.cpp \
  src-cpp/TopicPartitionImpl.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH) \
  $(MY_MODULE_PATH)/src \
  $(MY_MODULE_PATH)/src-cpp

LOCAL_CFLAGS := -DLIBRDKAFKACPP_EXPORTS -DLIBRDKAFKA_EXPORTS


LOCAL_LDLIBS := \
  -lzlib

include $(BUILD_SHARED_LIBRARY)

