--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: PatchSetGenerator


configuration( { "WIN32" } )
  project( "PatchSetGenerator" )

configuration( { "WIN64" } )
  project( "PatchSetGenerator" )
location( os.getenv( "PM4OUTPUTDIR" ) )
configuration( { "WIN32" } )
kind( "WindowedApp" )
configuration( { "WIN64" } )
kind( "WindowedApp" )

configuration( { "WIN32" } )
  links( { "gucefCORE", "gucefMT", "gucefPATCHER" } )
  links( { "gucefCORE", "gucefMT", "gucefPATCHER" } )
  defines( { "PATCHSETGENERATOR_BUILD_MODULE" } )

configuration( { "WIN64" } )
  links( { "gucefCORE", "gucefMT", "gucefPATCHER" } )
  links( { "gucefCORE", "gucefMT", "gucefPATCHER" } )
  defines( { "PATCHSETGENERATOR_BUILD_MODULE" } )


configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/PatchSetGenerator.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/PatchSetGenerator.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../gucefCOM/include", "../../gucefCOMCORE/include", "../../gucefCORE/include", "../../gucefMT/include", "../../gucefPATCHER/include" } )

configuration( { "WIN32" } )
includedirs( { "../../gucefCORE/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../gucefCORE/include/mswin" } )
