--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: aws-cpp-sdk-core


project( "aws-cpp-sdk-core" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "aws-c-common", "aws-c-event-stream", "aws-checksums", "curl" } )
links( { "aws-c-common", "aws-c-event-stream", "aws-checksums", "curl" } )


configuration( {} )
defines( { "AWS_CORE_EXPORTS=1", "USE_IMPORT_EXPORT=1" } )
  

configuration( { ANDROID } )
defines( { "ENABLE_OPENSSL_ENCRYPTION" } )
  

configuration( { LINUX32 } )
defines( { "ENABLE_OPENSSL_ENCRYPTION" } )
  

configuration( { LINUX64 } )
defines( { "ENABLE_OPENSSL_ENCRYPTION" } )
  

configuration( { OSX } )
defines( { "ENABLE_COMMONCRYPTO_ENCRYPTION" } )
  links( { "Userenv.lib", "Version.lib", "WindowsApp.lib", "Winhttp.lib", "Wininet.lib", "msxml6.lib" } )
  

configuration( { WIN32 } )
defines( { "BYPASS_DEFAULT_PROXY", "ENABLE_BCRYPT_ENCRYPTION", "ENABLE_WINDOWS_CLIENT", "ENABLE_WINDOWS_IXML_HTTP_REQUEST_2_CLIENT", "PLATFORM_WINDOWS" } )
  links( { "Userenv.lib", "Version.lib", "WindowsApp.lib", "Winhttp.lib", "Wininet.lib", "msxml6.lib" } )
  

configuration( { WIN64 } )
defines( { "BYPASS_DEFAULT_PROXY", "ENABLE_BCRYPT_ENCRYPTION", "ENABLE_WINDOWS_CLIENT", "ENABLE_WINDOWS_IXML_HTTP_REQUEST_2_CLIENT", "PLATFORM_WINDOWS" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/aws/core/AmazonSerializableWebServiceRequest.h",
  "include/aws/core/AmazonStreamingWebServiceRequest.h",
  "include/aws/core/AmazonWebServiceRequest.h",
  "include/aws/core/AmazonWebServiceResult.h",
  "include/aws/core/Aws.h",
  "include/aws/core/Core_EXPORTS.h",
  "include/aws/core/Globals.h",
  "include/aws/core/NoResult.h",
  "include/aws/core/Region.h",
  "include/aws/core/SDKConfig.h",
  "include/aws/core/Version.h",
  "include/aws/core/VersionConfig.h",
  "include/aws/core/auth/AWSAuthSigner.h",
  "include/aws/core/auth/AWSAuthSignerProvider.h",
  "include/aws/core/auth/AWSCredentials.h",
  "include/aws/core/auth/AWSCredentialsProvider.h",
  "include/aws/core/auth/AWSCredentialsProviderChain.h",
  "include/aws/core/auth/STSCredentialsProvider.h",
  "include/aws/core/client/AWSClient.h",
  "include/aws/core/client/AWSError.h",
  "include/aws/core/client/AWSErrorMarshaller.h",
  "include/aws/core/client/AsyncCallerContext.h",
  "include/aws/core/client/ClientConfiguration.h",
  "include/aws/core/client/CoreErrors.h",
  "include/aws/core/client/DefaultRetryStrategy.h",
  "include/aws/core/client/RetryStrategy.h",
  "include/aws/core/client/SpecifiedRetryableErrorsRetryStrategy.h",
  "include/aws/core/config/AWSProfileConfigLoader.h",
  "include/aws/core/external/cjson/cJSON.h",
  "include/aws/core/external/tinyxml2/tinyxml2.h",
  "include/aws/core/http/HttpClient.h",
  "include/aws/core/http/HttpClientFactory.h",
  "include/aws/core/http/HttpRequest.h",
  "include/aws/core/http/HttpResponse.h",
  "include/aws/core/http/HttpTypes.h",
  "include/aws/core/http/Scheme.h",
  "include/aws/core/http/URI.h",
  "include/aws/core/http/curl/CurlHandleContainer.h",
  "include/aws/core/http/curl/CurlHttpClient.h",
  "include/aws/core/http/standard/StandardHttpRequest.h",
  "include/aws/core/http/standard/StandardHttpResponse.h",
  "include/aws/core/internal/AWSHttpResourceClient.h",
  "include/aws/core/monitoring/CoreMetrics.h",
  "include/aws/core/monitoring/DefaultMonitoring.h",
  "include/aws/core/monitoring/HttpClientMetrics.h",
  "include/aws/core/monitoring/MonitoringFactory.h",
  "include/aws/core/monitoring/MonitoringInterface.h",
  "include/aws/core/monitoring/MonitoringManager.h",
  "include/aws/core/net/Net.h",
  "include/aws/core/net/SimpleUDP.h",
  "include/aws/core/platform/AWSTime.h",
  "include/aws/core/platform/Android.h",
  "include/aws/core/platform/Environment.h",
  "include/aws/core/platform/FileSystem.h",
  "include/aws/core/platform/OSVersionInfo.h",
  "include/aws/core/platform/Platform.h",
  "include/aws/core/platform/Security.h",
  "include/aws/core/platform/refs/IXmlHttpRequest2Ref.h",
  "include/aws/core/utils/ARN.h",
  "include/aws/core/utils/Array.h",
  "include/aws/core/utils/Cache.h",
  "include/aws/core/utils/ConcurrentCache.h",
  "include/aws/core/utils/DNS.h",
  "include/aws/core/utils/DateTime.h",
  "include/aws/core/utils/EnumParseOverflowContainer.h",
  "include/aws/core/utils/FileSystemUtils.h",
  "include/aws/core/utils/GetTheLights.h",
  "include/aws/core/utils/HashingUtils.h",
  "include/aws/core/utils/Outcome.h",
  "include/aws/core/utils/ResourceManager.h",
  "include/aws/core/utils/StringUtils.h",
  "include/aws/core/utils/UUID.h",
  "include/aws/core/utils/UnreferencedParam.h",
  "include/aws/core/utils/base64/Base64.h",
  "include/aws/core/utils/crypto/Cipher.h",
  "include/aws/core/utils/crypto/ContentCryptoMaterial.h",
  "include/aws/core/utils/crypto/ContentCryptoScheme.h",
  "include/aws/core/utils/crypto/CryptoBuf.h",
  "include/aws/core/utils/crypto/CryptoStream.h",
  "include/aws/core/utils/crypto/EncryptionMaterials.h",
  "include/aws/core/utils/crypto/Factories.h",
  "include/aws/core/utils/crypto/HMAC.h",
  "include/aws/core/utils/crypto/Hash.h",
  "include/aws/core/utils/crypto/HashResult.h",
  "include/aws/core/utils/crypto/KeyWrapAlgorithm.h",
  "include/aws/core/utils/crypto/MD5.h",
  "include/aws/core/utils/crypto/SecureRandom.h",
  "include/aws/core/utils/crypto/Sha256.h",
  "include/aws/core/utils/crypto/Sha256HMAC.h",
  "include/aws/core/utils/crypto/bcrypt/CryptoImpl.h",
  "include/aws/core/utils/crypto/commoncrypto/CryptoImpl.h",
  "include/aws/core/utils/crypto/openssl/CryptoImpl.h",
  "include/aws/core/utils/event/EventDecoderStream.h",
  "include/aws/core/utils/event/EventEncoderStream.h",
  "include/aws/core/utils/event/EventHeader.h",
  "include/aws/core/utils/event/EventMessage.h",
  "include/aws/core/utils/event/EventStream.h",
  "include/aws/core/utils/event/EventStreamBuf.h",
  "include/aws/core/utils/event/EventStreamDecoder.h",
  "include/aws/core/utils/event/EventStreamEncoder.h",
  "include/aws/core/utils/event/EventStreamErrors.h",
  "include/aws/core/utils/event/EventStreamHandler.h",
  "include/aws/core/utils/json/JsonSerializer.h",
  "include/aws/core/utils/logging/AWSLogging.h",
  "include/aws/core/utils/logging/ConsoleLogSystem.h",
  "include/aws/core/utils/logging/DefaultLogSystem.h",
  "include/aws/core/utils/logging/FormattedLogSystem.h",
  "include/aws/core/utils/logging/LogLevel.h",
  "include/aws/core/utils/logging/LogMacros.h",
  "include/aws/core/utils/logging/LogSystemInterface.h",
  "include/aws/core/utils/logging/NullLogSystem.h",
  "include/aws/core/utils/memory/AWSMemory.h",
  "include/aws/core/utils/memory/MemorySystemInterface.h",
  "include/aws/core/utils/memory/stl/AWSAllocator.h",
  "include/aws/core/utils/memory/stl/AWSDeque.h",
  "include/aws/core/utils/memory/stl/AWSList.h",
  "include/aws/core/utils/memory/stl/AWSMap.h",
  "include/aws/core/utils/memory/stl/AWSMultiMap.h",
  "include/aws/core/utils/memory/stl/AWSQueue.h",
  "include/aws/core/utils/memory/stl/AWSSet.h",
  "include/aws/core/utils/memory/stl/AWSStack.h",
  "include/aws/core/utils/memory/stl/AWSStreamFwd.h",
  "include/aws/core/utils/memory/stl/AWSString.h",
  "include/aws/core/utils/memory/stl/AWSStringStream.h",
  "include/aws/core/utils/memory/stl/AWSVector.h",
  "include/aws/core/utils/memory/stl/SimpleStringStream.h",
  "include/aws/core/utils/ratelimiter/DefaultRateLimiter.h",
  "include/aws/core/utils/ratelimiter/RateLimiterInterface.h",
  "include/aws/core/utils/stream/ConcurrentStreamBuf.h",
  "include/aws/core/utils/stream/PreallocatedStreamBuf.h",
  "include/aws/core/utils/stream/ResponseStream.h",
  "include/aws/core/utils/stream/SimpleStreamBuf.h",
  "include/aws/core/utils/threading/Executor.h",
  "include/aws/core/utils/threading/ReaderWriterLock.h",
  "include/aws/core/utils/threading/Semaphore.h",
  "include/aws/core/utils/threading/ThreadTask.h",
  "include/aws/core/utils/xml/XmlSerializer.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "source/AmazonSerializableWebServiceRequest.cpp",
  "source/AmazonStreamingWebServiceRequest.cpp",
  "source/AmazonWebServiceRequest.cpp",
  "source/Aws.cpp",
  "source/Globals.cpp",
  "source/Version.cpp",
  "source/auth/AWSAuthSigner.cpp",
  "source/auth/AWSAuthSignerProvider.cpp",
  "source/auth/AWSCredentialsProvider.cpp",
  "source/auth/AWSCredentialsProviderChain.cpp",
  "source/auth/STSCredentialsProvider.cpp",
  "source/client/AWSClient.cpp",
  "source/client/AWSErrorMarshaller.cpp",
  "source/client/AsyncCallerContext.cpp",
  "source/client/ClientConfiguration.cpp",
  "source/client/CoreErrors.cpp",
  "source/client/DefaultRetryStrategy.cpp",
  "source/client/SpecifiedRetryableErrorsRetryStrategy.cpp",
  "source/config/AWSProfileConfigLoader.cpp",
  "source/external/cjson/cJSON.cpp",
  "source/external/tinyxml2/tinyxml2.cpp",
  "source/http/HttpClient.cpp",
  "source/http/HttpClientFactory.cpp",
  "source/http/HttpRequest.cpp",
  "source/http/HttpTypes.cpp",
  "source/http/Scheme.cpp",
  "source/http/URI.cpp",
  "source/http/curl/CurlHandleContainer.cpp",
  "source/http/curl/CurlHttpClient.cpp",
  "source/http/standard/StandardHttpRequest.cpp",
  "source/http/standard/StandardHttpResponse.cpp",
  "source/internal/AWSHttpResourceClient.cpp",
  "source/monitoring/DefaultMonitoring.cpp",
  "source/monitoring/HttpClientMetrics.cpp",
  "source/monitoring/MonitoringManager.cpp",
  "source/utils/ARN.cpp",
  "source/utils/Array.cpp",
  "source/utils/DNS.cpp",
  "source/utils/DateTimeCommon.cpp",
  "source/utils/Directory.cpp",
  "source/utils/EnumParseOverflowContainer.cpp",
  "source/utils/FileSystemUtils.cpp",
  "source/utils/GetTheLights.cpp",
  "source/utils/HashingUtils.cpp",
  "source/utils/StringUtils.cpp",
  "source/utils/TempFile.cpp",
  "source/utils/UUID.cpp",
  "source/utils/base64/Base64.cpp",
  "source/utils/crypto/Cipher.cpp",
  "source/utils/crypto/ContentCryptoMaterial.cpp",
  "source/utils/crypto/ContentCryptoScheme.cpp",
  "source/utils/crypto/CryptoBuf.cpp",
  "source/utils/crypto/CryptoStream.cpp",
  "source/utils/crypto/EncryptionMaterials.cpp",
  "source/utils/crypto/KeyWrapAlgorithm.cpp",
  "source/utils/crypto/MD5.cpp",
  "source/utils/crypto/Sha256.cpp",
  "source/utils/crypto/Sha256HMAC.cpp",
  "source/utils/crypto/factory/Factories.cpp",
  "source/utils/event/EventDecoderStream.cpp",
  "source/utils/event/EventEncoderStream.cpp",
  "source/utils/event/EventHeader.cpp",
  "source/utils/event/EventMessage.cpp",
  "source/utils/event/EventStreamBuf.cpp",
  "source/utils/event/EventStreamDecoder.cpp",
  "source/utils/event/EventStreamEncoder.cpp",
  "source/utils/event/EventStreamErrors.cpp",
  "source/utils/json/JsonSerializer.cpp",
  "source/utils/logging/AWSLogging.cpp",
  "source/utils/logging/ConsoleLogSystem.cpp",
  "source/utils/logging/DefaultLogSystem.cpp",
  "source/utils/logging/FormattedLogSystem.cpp",
  "source/utils/logging/LogLevel.cpp",
  "source/utils/memory/AWSMemory.cpp",
  "source/utils/memory/stl/SimpleStringStream.cpp",
  "source/utils/stream/ConcurrentStreamBuf.cpp",
  "source/utils/stream/PreallocatedStreamBuf.cpp",
  "source/utils/stream/ResponseStream.cpp",
  "source/utils/stream/SimpleStreamBuf.cpp",
  "source/utils/threading/Executor.cpp",
  "source/utils/threading/ReaderWriterLock.cpp",
  "source/utils/threading/Semaphore.cpp",
  "source/utils/threading/ThreadTask.cpp",
  "source/utils/xml/XmlSerializer.cpp"
 } )



configuration( { "ANDROID" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/aws/core/utils/logging/android/LogcatLogSystem.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/platform/android/Environment.cpp",
      "source/platform/android/FileSystem.cpp",
      "source/platform/android/LogcatLogSystem.cpp",
      "source/platform/android/OSVersionInfo.cpp",
      "source/platform/android/Platform.cpp",
      "source/platform/android/Security.cpp",
      "source/platform/android/Time.cpp"
    } )



configuration( { "LINUX32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/net/linux-shared/Net.cpp",
      "source/net/linux-shared/SimpleUDP.cpp",
      "source/platform/linux-shared/Environment.cpp",
      "source/platform/linux-shared/FileSystem.cpp",
      "source/platform/linux-shared/OSVersionInfo.cpp",
      "source/platform/linux-shared/Security.cpp",
      "source/platform/linux-shared/Time.cpp",
      "source/utils/crypto/openssl/CryptoImpl.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/net/linux-shared/Net.cpp",
      "source/net/linux-shared/SimpleUDP.cpp",
      "source/platform/linux-shared/Environment.cpp",
      "source/platform/linux-shared/FileSystem.cpp",
      "source/platform/linux-shared/OSVersionInfo.cpp",
      "source/platform/linux-shared/Security.cpp",
      "source/platform/linux-shared/Time.cpp",
      "source/utils/crypto/openssl/CryptoImpl.cpp"
    } )



configuration( { "OSX" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/utils/crypto/commoncrypto/CryptoImpl.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/aws/core/http/windows/IXmlHttpRequest2HttpClient.h",
      "include/aws/core/http/windows/WinConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinHttpConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinHttpSyncHttpClient.h",
      "include/aws/core/http/windows/WinINetConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinINetSyncHttpClient.h",
      "include/aws/core/http/windows/WinSyncHttpClient.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/http/windows/IXmlHttpRequest2HttpClient.cpp",
      "source/http/windows/WinConnectionPoolMgr.cpp",
      "source/http/windows/WinHttpConnectionPoolMgr.cpp",
      "source/http/windows/WinHttpSyncHttpClient.cpp",
      "source/http/windows/WinINetConnectionPoolMgr.cpp",
      "source/http/windows/WinINetSyncHttpClient.cpp",
      "source/http/windows/WinSyncHttpClient.cpp",
      "source/net/windows/Net.cpp",
      "source/net/windows/SimpleUDP.cpp",
      "source/platform/windows/Environment.cpp",
      "source/platform/windows/FileSystem.cpp",
      "source/platform/windows/OSVersionInfo.cpp",
      "source/platform/windows/Security.cpp",
      "source/platform/windows/Time.cpp",
      "source/utils/crypto/bcrypt/CryptoImpl.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/aws/core/http/windows/IXmlHttpRequest2HttpClient.h",
      "include/aws/core/http/windows/WinConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinHttpConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinHttpSyncHttpClient.h",
      "include/aws/core/http/windows/WinINetConnectionPoolMgr.h",
      "include/aws/core/http/windows/WinINetSyncHttpClient.h",
      "include/aws/core/http/windows/WinSyncHttpClient.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "source/http/windows/IXmlHttpRequest2HttpClient.cpp",
      "source/http/windows/WinConnectionPoolMgr.cpp",
      "source/http/windows/WinHttpConnectionPoolMgr.cpp",
      "source/http/windows/WinHttpSyncHttpClient.cpp",
      "source/http/windows/WinINetConnectionPoolMgr.cpp",
      "source/http/windows/WinINetSyncHttpClient.cpp",
      "source/http/windows/WinSyncHttpClient.cpp",
      "source/net/windows/Net.cpp",
      "source/net/windows/SimpleUDP.cpp",
      "source/platform/windows/Environment.cpp",
      "source/platform/windows/FileSystem.cpp",
      "source/platform/windows/OSVersionInfo.cpp",
      "source/platform/windows/Security.cpp",
      "source/platform/windows/Time.cpp",
      "source/utils/crypto/bcrypt/CryptoImpl.cpp"
    } )


configuration( {} )
includedirs( { "../aws-c-common/include", "../aws-c-event-stream/include", "../aws-checksums/include", "../aws-checksums/include/aws", "../aws-checksums/include/aws/checksums", "../aws-checksums/include/aws/checksums/private", "../curl/include", "../curl/include/curl", "../curl/lib", "../curl/lib/vauth", "../curl/lib/vquic", "../curl/lib/vssh", "../curl/lib/vtls", "include", "include/aws", "include/aws/core/external", "include/aws/core", "include/aws/core/auth", "include/aws/core/client", "include/aws/core/config", "include/aws/core/external/cjson", "include/aws/core/external/tinyxml2", "include/aws/core/http", "include/aws/core/http/curl", "include/aws/core/http/standard", "include/aws/core/internal", "include/aws/core/monitoring", "include/aws/core/net", "include/aws/core/platform", "include/aws/core/platform/refs", "include/aws/core/utils", "include/aws/core/utils/base64", "include/aws/core/utils/crypto", "include/aws/core/utils/crypto/bcrypt", "include/aws/core/utils/crypto/commoncrypto", "include/aws/core/utils/crypto/openssl", "include/aws/core/utils/event", "include/aws/core/utils/json", "include/aws/core/utils/logging", "include/aws/core/utils/memory", "include/aws/core/utils/memory/stl", "include/aws/core/utils/ratelimiter", "include/aws/core/utils/stream", "include/aws/core/utils/threading", "include/aws/core/utils/xml" } )

configuration( { "ANDROID" } )
includedirs( { "include/aws/core/utils/logging/android" } )

configuration( { "WIN32" } )
includedirs( { "../curl/lib", "include/aws/core/http/windows" } )

configuration( { "WIN64" } )
includedirs( { "../curl/lib", "include/aws/core/http/windows" } )
