#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := OgreRenderSystem_GL
LOCAL_MODULE_FILENAME := libOgreRenderSystem_GL
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/OgreGLATIFSInit.cpp \
  src/OgreGLContext.cpp \
  src/OgreGLDefaultHardwareBufferManager.cpp \
  src/OgreGLDepthBuffer.cpp \
  src/OgreGLEngineDll.cpp \
  src/OgreGLFBOMultiRenderTarget.cpp \
  src/OgreGLFBORenderTexture.cpp \
  src/OgreGLFrameBufferObject.cpp \
  src/OgreGLGpuNvparseProgram.cpp \
  src/OgreGLGpuProgram.cpp \
  src/OgreGLGpuProgramManager.cpp \
  src/OgreGLHardwareBufferManager.cpp \
  src/OgreGLHardwareIndexBuffer.cpp \
  src/OgreGLHardwareOcclusionQuery.cpp \
  src/OgreGLHardwarePixelBuffer.cpp \
  src/OgreGLHardwareVertexBuffer.cpp \
  src/OgreGLPBRenderTexture.cpp \
  src/OgreGLPixelFormat.cpp \
  src/OgreGLPlugin.cpp \
  src/OgreGLRenderSystem.cpp \
  src/OgreGLRenderTexture.cpp \
  src/OgreGLRenderToVertexBuffer.cpp \
  src/OgreGLStateCacheManager.cpp \
  src/OgreGLSupport.cpp \
  src/OgreGLTexture.cpp \
  src/OgreGLTextureManager.cpp \
  src/OgreGLUniformCache.cpp \
  src/glew.cpp \
  src/GLSL/src/OgreGLSLExtSupport.cpp \
  src/GLSL/src/OgreGLSLGpuProgram.cpp \
  src/GLSL/src/OgreGLSLLinkProgram.cpp \
  src/GLSL/src/OgreGLSLLinkProgramManager.cpp \
  src/GLSL/src/OgreGLSLPreprocessor.cpp \
  src/GLSL/src/OgreGLSLProgram.cpp \
  src/GLSL/src/OgreGLSLProgramFactory.cpp \
  src/StateCacheManager/OgreGLNullStateCacheManagerImp.cpp \
  src/StateCacheManager/OgreGLNullUniformCacheImp.cpp \
  src/atifs/src/ATI_FS_GLGpuProgram.cpp \
  src/atifs/src/Compiler2Pass.cpp \
  src/atifs/src/ps_1_4.cpp \
  src/nvparse/_ps1.0_lexer.cpp \
  src/nvparse/_ps1.0_parser.cpp \
  src/nvparse/_rc1.0_lexer.cpp \
  src/nvparse/_rc1.0_parser.cpp \
  src/nvparse/_ts1.0_lexer.cpp \
  src/nvparse/_ts1.0_parser.cpp \
  src/nvparse/_vs1.0_lexer.cpp \
  src/nvparse/_vs1.0_parser.cpp \
  src/nvparse/avp1.0_impl.cpp \
  src/nvparse/nvparse.cpp \
  src/nvparse/nvparse_errors.cpp \
  src/nvparse/ps1.0_program.cpp \
  src/nvparse/rc1.0_combiners.cpp \
  src/nvparse/rc1.0_final.cpp \
  src/nvparse/rc1.0_general.cpp \
  src/nvparse/ts1.0_inst.cpp \
  src/nvparse/ts1.0_inst_list.cpp \
  src/nvparse/vcp1.0_impl.cpp \
  src/nvparse/vp1.0_impl.cpp \
  src/nvparse/vs1.0_inst.cpp \
  src/nvparse/vs1.0_inst_list.cpp \
  src/nvparse/vsp1.0_impl.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/GL \
  $(MY_MODULE_PATH)/src/GLSL/include \
  $(MY_MODULE_PATH)/src/StateCacheManager \
  $(MY_MODULE_PATH)/src/atifs/include \
  $(MY_MODULE_PATH)/src/nvparse \
  $(MY_MODULE_PATH)/src/nvparse/winheaders \
  $(MY_MODULE_PATH)/../../../freetype/include \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../freetype/src \
  $(MY_MODULE_PATH)/../../../freetype/src/winfonts \
  $(MY_MODULE_PATH)/../../OgreMain/include \
  $(MY_MODULE_PATH)/../../OgreMain/include/Android \
  $(MY_MODULE_PATH)/../../OgreMain/include/Hash \
  $(MY_MODULE_PATH)/../../OgreMain/include/Threading \
  $(MY_MODULE_PATH)/../../OgreMain/src \
  $(MY_MODULE_PATH)/../../OgreMain/src/nedmalloc \
  $(MY_MODULE_PATH)/../../OgreMain/src/stbi \
  $(MY_MODULE_PATH)/../../include \
  $(MY_MODULE_PATH)/src \
  $(MY_MODULE_PATH)/src/GLSL \
  $(MY_MODULE_PATH)/src/atifs

LOCAL_CFLAGS := -DOGRE_GLPLUGIN_EXPORTS


LOCAL_SHARED_LIBRARIES := \
  Ogre

include $(BUILD_SHARED_LIBRARY)

