--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MemoryLeakFinder_TestApp


configuration( { "WIN32" } )
  project( "MemoryLeakFinder_TestApp" )

configuration( { "WIN64" } )
  project( "MemoryLeakFinder_TestApp" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "WindowedApp" )
  
configuration( { WIN32 } )
links( { "MemoryLeakFinder", "gucefCORE", "gucefMT" } )
  links( { "gucefCORE", "gucefMT" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_MLF_TESTAPP_BUILD_MODULE", "MEMCHECK_OLEAPI" } )
  
configuration( { WIN64 } )
links( { "MemoryLeakFinder", "gucefCORE", "gucefMT" } )
  links( { "gucefCORE", "gucefMT" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_MLF_TESTAPP_BUILD_MODULE", "MEMCHECK_OLEAPI" } )


configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryLeakFinder_TestApp.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryLeakFinder_TestApp.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCORE/include", "../../platform/gucefMT/include" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin", "../../platform/gucefMT/include/mswin/", "../../tools/MemoryLeakFinder/include" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin", "../../platform/gucefMT/include/mswin/", "../../tools/MemoryLeakFinder/include" } )
