#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := OpenEXR
LOCAL_MODULE_FILENAME := libOpenEXR
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  IlmBase/Half/half.cpp \
  IlmBase/Iex/IexBaseExc.cpp \
  IlmBase/Iex/IexThrowErrnoExc.cpp \
  IlmBase/IexMath/IexMathFloatExc.cpp \
  IlmBase/IexMath/IexMathFpu.cpp \
  IlmBase/IlmThread/IlmThread.cpp \
  IlmBase/IlmThread/IlmThreadMutex.cpp \
  IlmBase/IlmThread/IlmThreadMutexPosix.cpp \
  IlmBase/IlmThread/IlmThreadMutexWin32.cpp \
  IlmBase/IlmThread/IlmThreadPool.cpp \
  IlmBase/IlmThread/IlmThreadPosix.cpp \
  IlmBase/IlmThread/IlmThreadSemaphore.cpp \
  IlmBase/IlmThread/IlmThreadSemaphorePosix.cpp \
  IlmBase/IlmThread/IlmThreadSemaphorePosixCompat.cpp \
  IlmBase/IlmThread/IlmThreadSemaphoreWin32.cpp \
  IlmBase/IlmThread/IlmThreadWin32.cpp \
  IlmBase/Imath/ImathBox.cpp \
  IlmBase/Imath/ImathColorAlgo.cpp \
  IlmBase/Imath/ImathFun.cpp \
  IlmBase/Imath/ImathMatrixAlgo.cpp \
  IlmBase/Imath/ImathRandom.cpp \
  IlmBase/Imath/ImathShear.cpp \
  IlmBase/Imath/ImathVec.cpp \
  OpenEXR/IlmImf/ImfAcesFile.cpp \
  OpenEXR/IlmImf/ImfAttribute.cpp \
  OpenEXR/IlmImf/ImfB44Compressor.cpp \
  OpenEXR/IlmImf/ImfBoxAttribute.cpp \
  OpenEXR/IlmImf/ImfCRgbaFile.cpp \
  OpenEXR/IlmImf/ImfChannelList.cpp \
  OpenEXR/IlmImf/ImfChannelListAttribute.cpp \
  OpenEXR/IlmImf/ImfChromaticities.cpp \
  OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp \
  OpenEXR/IlmImf/ImfCompositeDeepScanLine.cpp \
  OpenEXR/IlmImf/ImfCompressionAttribute.cpp \
  OpenEXR/IlmImf/ImfCompressor.cpp \
  OpenEXR/IlmImf/ImfConvert.cpp \
  OpenEXR/IlmImf/ImfDeepCompositing.cpp \
  OpenEXR/IlmImf/ImfDeepFrameBuffer.cpp \
  OpenEXR/IlmImf/ImfDeepImageStateAttribute.cpp \
  OpenEXR/IlmImf/ImfDeepScanLineInputFile.cpp \
  OpenEXR/IlmImf/ImfDeepScanLineInputPart.cpp \
  OpenEXR/IlmImf/ImfDeepScanLineOutputFile.cpp \
  OpenEXR/IlmImf/ImfDeepScanLineOutputPart.cpp \
  OpenEXR/IlmImf/ImfDeepTiledInputFile.cpp \
  OpenEXR/IlmImf/ImfDeepTiledInputPart.cpp \
  OpenEXR/IlmImf/ImfDeepTiledOutputFile.cpp \
  OpenEXR/IlmImf/ImfDeepTiledOutputPart.cpp \
  OpenEXR/IlmImf/ImfDoubleAttribute.cpp \
  OpenEXR/IlmImf/ImfDwaCompressor.cpp \
  OpenEXR/IlmImf/ImfEnvmap.cpp \
  OpenEXR/IlmImf/ImfEnvmapAttribute.cpp \
  OpenEXR/IlmImf/ImfFastHuf.cpp \
  OpenEXR/IlmImf/ImfFloatAttribute.cpp \
  OpenEXR/IlmImf/ImfFloatVectorAttribute.cpp \
  OpenEXR/IlmImf/ImfFrameBuffer.cpp \
  OpenEXR/IlmImf/ImfFramesPerSecond.cpp \
  OpenEXR/IlmImf/ImfGenericInputFile.cpp \
  OpenEXR/IlmImf/ImfGenericOutputFile.cpp \
  OpenEXR/IlmImf/ImfHeader.cpp \
  OpenEXR/IlmImf/ImfHuf.cpp \
  OpenEXR/IlmImf/ImfIO.cpp \
  OpenEXR/IlmImf/ImfInputFile.cpp \
  OpenEXR/IlmImf/ImfInputPart.cpp \
  OpenEXR/IlmImf/ImfInputPartData.cpp \
  OpenEXR/IlmImf/ImfIntAttribute.cpp \
  OpenEXR/IlmImf/ImfKeyCode.cpp \
  OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp \
  OpenEXR/IlmImf/ImfLineOrderAttribute.cpp \
  OpenEXR/IlmImf/ImfLut.cpp \
  OpenEXR/IlmImf/ImfMatrixAttribute.cpp \
  OpenEXR/IlmImf/ImfMisc.cpp \
  OpenEXR/IlmImf/ImfMultiPartInputFile.cpp \
  OpenEXR/IlmImf/ImfMultiPartOutputFile.cpp \
  OpenEXR/IlmImf/ImfMultiView.cpp \
  OpenEXR/IlmImf/ImfOpaqueAttribute.cpp \
  OpenEXR/IlmImf/ImfOutputFile.cpp \
  OpenEXR/IlmImf/ImfOutputPart.cpp \
  OpenEXR/IlmImf/ImfOutputPartData.cpp \
  OpenEXR/IlmImf/ImfPartType.cpp \
  OpenEXR/IlmImf/ImfPizCompressor.cpp \
  OpenEXR/IlmImf/ImfPreviewImage.cpp \
  OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp \
  OpenEXR/IlmImf/ImfPxr24Compressor.cpp \
  OpenEXR/IlmImf/ImfRational.cpp \
  OpenEXR/IlmImf/ImfRationalAttribute.cpp \
  OpenEXR/IlmImf/ImfRgbaFile.cpp \
  OpenEXR/IlmImf/ImfRgbaYca.cpp \
  OpenEXR/IlmImf/ImfRle.cpp \
  OpenEXR/IlmImf/ImfRleCompressor.cpp \
  OpenEXR/IlmImf/ImfScanLineInputFile.cpp \
  OpenEXR/IlmImf/ImfStandardAttributes.cpp \
  OpenEXR/IlmImf/ImfStdIO.cpp \
  OpenEXR/IlmImf/ImfStringAttribute.cpp \
  OpenEXR/IlmImf/ImfStringVectorAttribute.cpp \
  OpenEXR/IlmImf/ImfSystemSpecific.cpp \
  OpenEXR/IlmImf/ImfTestFile.cpp \
  OpenEXR/IlmImf/ImfThreading.cpp \
  OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp \
  OpenEXR/IlmImf/ImfTileOffsets.cpp \
  OpenEXR/IlmImf/ImfTiledInputFile.cpp \
  OpenEXR/IlmImf/ImfTiledInputPart.cpp \
  OpenEXR/IlmImf/ImfTiledMisc.cpp \
  OpenEXR/IlmImf/ImfTiledOutputFile.cpp \
  OpenEXR/IlmImf/ImfTiledOutputPart.cpp \
  OpenEXR/IlmImf/ImfTiledRgbaFile.cpp \
  OpenEXR/IlmImf/ImfTimeCode.cpp \
  OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp \
  OpenEXR/IlmImf/ImfVecAttribute.cpp \
  OpenEXR/IlmImf/ImfVersion.cpp \
  OpenEXR/IlmImf/ImfWav.cpp \
  OpenEXR/IlmImf/ImfZip.cpp \
  OpenEXR/IlmImf/ImfZipCompressor.cpp \
  OpenEXR/IlmImfUtil/ImfDeepImage.cpp \
  OpenEXR/IlmImfUtil/ImfDeepImageChannel.cpp \
  OpenEXR/IlmImfUtil/ImfDeepImageIO.cpp \
  OpenEXR/IlmImfUtil/ImfDeepImageLevel.cpp \
  OpenEXR/IlmImfUtil/ImfFlatImage.cpp \
  OpenEXR/IlmImfUtil/ImfFlatImageChannel.cpp \
  OpenEXR/IlmImfUtil/ImfFlatImageIO.cpp \
  OpenEXR/IlmImfUtil/ImfFlatImageLevel.cpp \
  OpenEXR/IlmImfUtil/ImfImage.cpp \
  OpenEXR/IlmImfUtil/ImfImageChannel.cpp \
  OpenEXR/IlmImfUtil/ImfImageDataWindow.cpp \
  OpenEXR/IlmImfUtil/ImfImageIO.cpp \
  OpenEXR/IlmImfUtil/ImfImageLevel.cpp \
  OpenEXR/IlmImfUtil/ImfSampleCountChannel.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/IlmBase/Half \
  $(MY_MODULE_PATH)/IlmBase/Iex \
  $(MY_MODULE_PATH)/IlmBase/IexMath \
  $(MY_MODULE_PATH)/IlmBase/IlmThread \
  $(MY_MODULE_PATH)/IlmBase/Imath \
  $(MY_MODULE_PATH)/IlmBase/config.windows \
  $(MY_MODULE_PATH)/OpenEXR/IlmImf \
  $(MY_MODULE_PATH)/OpenEXR/IlmImfUtil \
  $(MY_MODULE_PATH)/OpenEXR/config.windows \
  $(MY_MODULE_PATH)/IlmBase \
  $(MY_MODULE_PATH)/OpenEXR


LOCAL_LDLIBS := \
  -lzlib

include $(BUILD_SHARED_LIBRARY)

