--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: imgpluginFreeImage


configuration( { "LINUX" } )
  project( "imgpluginFreeImage" )

configuration( { "WIN32" } )
  project( "imgpluginFreeImage" )

configuration( { "WIN64" } )
  project( "imgpluginFreeImage" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX" } )


configuration( { LINUX } )
kind( "SharedLib" )
configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )
  
configuration( { LINUX } )
links( { "FreeImage", "gucefCORE", "gucefIMAGE", "gucefMT" } )
  links( { "FreeImage" } )
  

configuration( { LINUX } )
defines( { "GUCEF_CODECPLUGIN_BUILD_MODULE" } )
  
configuration( { WIN32 } )
links( { "FreeImage", "gucefCORE", "gucefIMAGE", "gucefMT" } )
  links( { "FreeImage" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_CODECPLUGIN_BUILD_MODULE" } )
  
configuration( { WIN64 } )
links( { "FreeImage", "gucefCORE", "gucefIMAGE", "gucefMT" } )
  links( { "FreeImage" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_CODECPLUGIN_BUILD_MODULE" } )


configuration( { "LINUX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/imgpluginFreeImage.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/imgpluginFreeImage.c"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/imgpluginFreeImage.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/imgpluginFreeImage.c"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/imgpluginFreeImage.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/imgpluginFreeImage.c"
    } )


configuration( {} )
includedirs( { "../../../common/include", "../../../gucefCORE/include", "../../../gucefIMAGE/include", "../../../gucefMT/include" } )

configuration( { "LINUX" } )
includedirs( { "../../../dependencies/FreeImage/Source", "../../../dependencies/FreeImage/Source/DeprecationManager", "../../../dependencies/FreeImage/Source/FreeImageToolkit", "../../../dependencies/FreeImage/Source/LibJPEG", "../../../dependencies/FreeImage/Source/LibMNG", "../../../dependencies/FreeImage/Source/LibOpenJPEG", "../../../dependencies/FreeImage/Source/LibPNG", "../../../dependencies/FreeImage/Source/LibTIFF", "../../../dependencies/FreeImage/Source/Metadata", "../../../dependencies/FreeImage/Source/OpenEXR", "../../../dependencies/FreeImage/Source/OpenEXR/Half", "../../../dependencies/FreeImage/Source/OpenEXR/Iex", "../../../dependencies/FreeImage/Source/OpenEXR/IlmImf", "../../../dependencies/FreeImage/Source/OpenEXR/IlmThread", "../../../dependencies/FreeImage/Source/OpenEXR/Imath", "../../../dependencies/FreeImage/Source/ZLib", "../../../gucefCORE/include/linux", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/FreeImage/Source", "../../../dependencies/FreeImage/Source/DeprecationManager", "../../../dependencies/FreeImage/Source/FreeImageToolkit", "../../../dependencies/FreeImage/Source/LibJPEG", "../../../dependencies/FreeImage/Source/LibMNG", "../../../dependencies/FreeImage/Source/LibOpenJPEG", "../../../dependencies/FreeImage/Source/LibPNG", "../../../dependencies/FreeImage/Source/LibTIFF", "../../../dependencies/FreeImage/Source/Metadata", "../../../dependencies/FreeImage/Source/OpenEXR", "../../../dependencies/FreeImage/Source/OpenEXR/Half", "../../../dependencies/FreeImage/Source/OpenEXR/Iex", "../../../dependencies/FreeImage/Source/OpenEXR/IlmImf", "../../../dependencies/FreeImage/Source/OpenEXR/IlmThread", "../../../dependencies/FreeImage/Source/OpenEXR/Imath", "../../../dependencies/FreeImage/Source/ZLib", "../../../gucefCORE/include/mswin", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/FreeImage/Source", "../../../dependencies/FreeImage/Source/DeprecationManager", "../../../dependencies/FreeImage/Source/FreeImageToolkit", "../../../dependencies/FreeImage/Source/LibJPEG", "../../../dependencies/FreeImage/Source/LibMNG", "../../../dependencies/FreeImage/Source/LibOpenJPEG", "../../../dependencies/FreeImage/Source/LibPNG", "../../../dependencies/FreeImage/Source/LibTIFF", "../../../dependencies/FreeImage/Source/Metadata", "../../../dependencies/FreeImage/Source/OpenEXR", "../../../dependencies/FreeImage/Source/OpenEXR/Half", "../../../dependencies/FreeImage/Source/OpenEXR/Iex", "../../../dependencies/FreeImage/Source/OpenEXR/IlmImf", "../../../dependencies/FreeImage/Source/OpenEXR/IlmThread", "../../../dependencies/FreeImage/Source/OpenEXR/Imath", "../../../dependencies/FreeImage/Source/ZLib", "../../../gucefCORE/include/mswin", "include" } )
