#-------------------------------------------------------------------
# This file was automatically generated by ProjectGenerator
# which is tooling part the build system designed for GUCEF
#     (Galaxy Unlimited Framework)
# For the latest info, see http://www.VanvelzenSoftware.com/
#
# The contents of this file are placed in the public domain. Feel
# free to make use of it in any way you like.
#-------------------------------------------------------------------
#


option( TAGGED_BUILD_OPTION_obsolete "build option based on tag obsolete" ON)
option( TAGGED_BUILD_OPTION_platform "build option based on tag platform" ON)
option( TAGGED_BUILD_OPTION_plugin "build option based on tag plugin" ON)
option( TAGGED_BUILD_OPTION_test "build option based on tag test" ON)


message( STATUS "TAGGED_BUILD_OPTION_obsolete: ${TAGGED_BUILD_OPTION_obsolete} )
message( STATUS "TAGGED_BUILD_OPTION_platform: ${TAGGED_BUILD_OPTION_platform} )
message( STATUS "TAGGED_BUILD_OPTION_plugin: ${TAGGED_BUILD_OPTION_plugin} )
message( STATUS "TAGGED_BUILD_OPTION_test: ${TAGGED_BUILD_OPTION_test} )
