--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_gucefKAITAI_TestApp" )

  platforms( { "ALL" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libparsifal" )
  include( "dependencies/libyaml" )
  include( "dependencies/stbrumme-hash-library" )
  include( "dependencies/zlib" )
  include( "dependencies/zziplib" )
  include( "platform/gucefCORE" )
  include( "platform/gucefKAITAI" )
  include( "platform/gucefMT" )
  include( "platform/gucefVFS" )
  include( "plugins/CORE/codecspluginSTBRUMMEHASH" )
  include( "plugins/CORE/codecspluginZLIB" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/CORE/dstorepluginYAML" )
  include( "plugins/VFS/vfspluginZIP" )
  include( "tests/gucefKAITAI_TestApp" )
