--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: CEGUI


project( "CEGUI" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "freetype", "pcre" } )
links( { "freetype", "pcre" } )


configuration( {} )
defines( { "CEGUIBASE_EXPORTS" } )
  links( { "Dbghelp", "Winmm" } )
  links( { "Dbghelp", "Winmm" } )


configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/Affector.cpp",
  "src/Animation.cpp",
  "src/AnimationInstance.cpp",
  "src/AnimationManager.cpp",
  "src/Animation_xmlHandler.cpp",
  "src/Base.cpp",
  "src/BasicImage.cpp",
  "src/BasicRenderedStringParser.cpp",
  "src/BidiVisualMapping.cpp",
  "src/BoundSlot.cpp",
  "src/CentredRenderedString.cpp",
  "src/ChainedXMLHandler.cpp",
  "src/Clipboard.cpp",
  "src/Colour.cpp",
  "src/ColourRect.cpp",
  "src/CompositeResourceProvider.cpp",
  "src/Config_xmlHandler.cpp",
  "src/CoordConverter.cpp",
  "src/DataContainer.cpp",
  "src/DefaultLogger.cpp",
  "src/DefaultRenderedStringParser.cpp",
  "src/DefaultResourceProvider.cpp",
  "src/DynamicModule.cpp",
  "src/Element.cpp",
  "src/Event.cpp",
  "src/EventArgs.cpp",
  "src/EventSet.cpp",
  "src/Exceptions.cpp",
  "src/FactoryModule.cpp",
  "src/FactoryRegisterer.cpp",
  "src/Font.cpp",
  "src/FontManager.cpp",
  "src/Font_xmlHandler.cpp",
  "src/FormattedRenderedString.cpp",
  "src/FreeTypeFont.cpp",
  "src/FribidiVisualMapping.cpp",
  "src/GUIContext.cpp",
  "src/GUILayout_xmlHandler.cpp",
  "src/GeometryBuffer.cpp",
  "src/GlobalEventSet.cpp",
  "src/Image.cpp",
  "src/ImageCodec.cpp",
  "src/ImageManager.cpp",
  "src/JustifiedRenderedString.cpp",
  "src/JustifiedRenderedStringWordWrapper.cpp",
  "src/KeyFrame.cpp",
  "src/LeftAlignedRenderedString.cpp",
  "src/LinkedEvent.cpp",
  "src/Logger.cpp",
  "src/MinibidiVisualMapping.cpp",
  "src/MinizipResourceProvider.cpp",
  "src/MouseCursor.cpp",
  "src/NamedElement.cpp",
  "src/NamedXMLResourceManager.cpp",
  "src/PCRERegexMatcher.cpp",
  "src/PixmapFont.cpp",
  "src/Property.cpp",
  "src/PropertyHelper.cpp",
  "src/PropertySet.cpp",
  "src/Quaternion.cpp",
  "src/Rect.cpp",
  "src/RenderEffectManager.cpp",
  "src/RenderQueue.cpp",
  "src/RenderTarget.cpp",
  "src/RenderedString.cpp",
  "src/RenderedStringComponent.cpp",
  "src/RenderedStringImageComponent.cpp",
  "src/RenderedStringTextComponent.cpp",
  "src/RenderedStringWidgetComponent.cpp",
  "src/RenderingSurface.cpp",
  "src/RenderingWindow.cpp",
  "src/RightAlignedRenderedString.cpp",
  "src/Scheme.cpp",
  "src/SchemeManager.cpp",
  "src/Scheme_xmlHandler.cpp",
  "src/ScriptModule.cpp",
  "src/SimpleTimer.cpp",
  "src/String.cpp",
  "src/SubscriberSlot.cpp",
  "src/System.cpp",
  "src/SystemKeys.cpp",
  "src/TextUtils.cpp",
  "src/Window.cpp",
  "src/WindowFactory.cpp",
  "src/WindowFactoryManager.cpp",
  "src/WindowManager.cpp",
  "src/WindowRenderer.cpp",
  "src/WindowRendererManager.cpp",
  "src/XMLAttributes.cpp",
  "src/XMLHandler.cpp",
  "src/XMLParser.cpp",
  "src/XMLSerializer.cpp",
  "src/minibidi.cpp",
  "src/falagard/ComponentBase.cpp",
  "src/falagard/Dimensions.cpp",
  "src/falagard/EventAction.cpp",
  "src/falagard/EventLinkDefinition.cpp",
  "src/falagard/FormattingSetting.cpp",
  "src/falagard/FrameComponent.cpp",
  "src/falagard/ImageryComponent.cpp",
  "src/falagard/ImagerySection.cpp",
  "src/falagard/LayerSpecification.cpp",
  "src/falagard/NamedArea.cpp",
  "src/falagard/PropertyDefinitionBase.cpp",
  "src/falagard/PropertyInitialiser.cpp",
  "src/falagard/SectionSpecification.cpp",
  "src/falagard/StateImagery.cpp",
  "src/falagard/TextComponent.cpp",
  "src/falagard/WidgetComponent.cpp",
  "src/falagard/WidgetLookFeel.cpp",
  "src/falagard/WidgetLookManager.cpp",
  "src/falagard/XMLEnumHelper.cpp",
  "src/falagard/XMLHandler.cpp",
  "src/widgets/ButtonBase.cpp",
  "src/widgets/ClippedContainer.cpp",
  "src/widgets/ComboDropList.cpp",
  "src/widgets/Combobox.cpp",
  "src/widgets/DefaultWindow.cpp",
  "src/widgets/DragContainer.cpp",
  "src/widgets/Editbox.cpp",
  "src/widgets/FrameWindow.cpp",
  "src/widgets/GridLayoutContainer.cpp",
  "src/widgets/GroupBox.cpp",
  "src/widgets/HorizontalLayoutContainer.cpp",
  "src/widgets/ItemEntry.cpp",
  "src/widgets/ItemListBase.cpp",
  "src/widgets/ItemListbox.cpp",
  "src/widgets/LayoutCell.cpp",
  "src/widgets/LayoutContainer.cpp",
  "src/widgets/ListHeader.cpp",
  "src/widgets/ListHeaderSegment.cpp",
  "src/widgets/Listbox.cpp",
  "src/widgets/ListboxItem.cpp",
  "src/widgets/ListboxTextItem.cpp",
  "src/widgets/MenuBase.cpp",
  "src/widgets/MenuItem.cpp",
  "src/widgets/Menubar.cpp",
  "src/widgets/MultiColumnList.cpp",
  "src/widgets/MultiLineEditbox.cpp",
  "src/widgets/PopupMenu.cpp",
  "src/widgets/ProgressBar.cpp",
  "src/widgets/PushButton.cpp",
  "src/widgets/RadioButton.cpp",
  "src/widgets/ScrollablePane.cpp",
  "src/widgets/Scrollbar.cpp",
  "src/widgets/ScrolledContainer.cpp",
  "src/widgets/ScrolledItemListBase.cpp",
  "src/widgets/SequentialLayoutContainer.cpp",
  "src/widgets/Slider.cpp",
  "src/widgets/Spinner.cpp",
  "src/widgets/TabButton.cpp",
  "src/widgets/TabControl.cpp",
  "src/widgets/Thumb.cpp",
  "src/widgets/Titlebar.cpp",
  "src/widgets/ToggleButton.cpp",
  "src/widgets/Tooltip.cpp",
  "src/widgets/Tree.cpp",
  "src/widgets/TreeItem.cpp",
  "src/widgets/VerticalLayoutContainer.cpp"
 } )



configuration( { "ANDROID" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/IconvStringTranscoder.cpp"
    } )



configuration( { "LINUX32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/IconvStringTranscoder.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/IconvStringTranscoder.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/Win32StringTranscoder.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/Win32StringTranscoder.cpp"
    } )


configuration( {} )
includedirs( { "../../freetype/include", "../../freetype/include/freetype", "../../freetype/include/freetype/config", "../../freetype/include/freetype/internal", "../../freetype/include/freetype/internal/services", "../../freetype/src", "../../freetype/src/winfonts", "../../pcre", "include" } )
