#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := RocketControls
LOCAL_MODULE_FILENAME := libRocketControls
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  Clipboard.cpp \
  Controls.cpp \
  DataFormatter.cpp \
  DataQuery.cpp \
  DataSource.cpp \
  DataSourceListener.cpp \
  ElementDataGrid.cpp \
  ElementDataGridCell.cpp \
  ElementDataGridExpandButton.cpp \
  ElementDataGridRow.cpp \
  ElementForm.cpp \
  ElementFormControl.cpp \
  ElementFormControlDataSelect.cpp \
  ElementFormControlInput.cpp \
  ElementFormControlSelect.cpp \
  ElementFormControlTextArea.cpp \
  ElementTabSet.cpp \
  ElementTextSelection.cpp \
  InputType.cpp \
  InputTypeButton.cpp \
  InputTypeCheckbox.cpp \
  InputTypeRadio.cpp \
  InputTypeRange.cpp \
  InputTypeSubmit.cpp \
  InputTypeText.cpp \
  SelectOption.cpp \
  WidgetDropDown.cpp \
  WidgetSlider.cpp \
  WidgetSliderInput.cpp \
  WidgetTextInput.cpp \
  WidgetTextInputMultiLine.cpp \
  WidgetTextInputSingleLine.cpp \
  WidgetTextInputSingleLinePassword.cpp \
  XMLNodeHandlerDataGrid.cpp \
  XMLNodeHandlerTabSet.cpp \
  XMLNodeHandlerTextArea.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH) \
  $(MY_MODULE_PATH)/../../../freetype/include \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../freetype/src/winfonts \
  $(MY_MODULE_PATH)/../../Include \
  $(MY_MODULE_PATH)/../../Include/Rocket \
  $(MY_MODULE_PATH)/../../Include/Rocket/Controls \
  $(MY_MODULE_PATH)/../../Include/Rocket/Core \
  $(MY_MODULE_PATH)/../../Include/Rocket/Core/Python \
  $(MY_MODULE_PATH)/../../Include/Rocket/Debugger \
  $(MY_MODULE_PATH)/../Core

LOCAL_CPPFLAGS +=-frtti


LOCAL_SHARED_LIBRARIES := \
  RocketCore \
  freetype

include $(BUILD_SHARED_LIBRARY)

