/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue */

#ifndef _Included_com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue
#define _Included_com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue
 * Method:    Main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue_Main
  (JNIEnv *, jobject);

/*
 * Class:     com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_VanvelzenSoftware_gucefANDROIDGLUE_GUCEFApplicationGlue_Stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
