#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := pcre
LOCAL_MODULE_FILENAME := libpcre
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  pcre16_byte_order.c \
  pcre16_chartables.c \
  pcre16_compile.c \
  pcre16_config.c \
  pcre16_dfa_exec.c \
  pcre16_exec.c \
  pcre16_fullinfo.c \
  pcre16_get.c \
  pcre16_globals.c \
  pcre16_jit_compile.c \
  pcre16_maketables.c \
  pcre16_newline.c \
  pcre16_ord2utf16.c \
  pcre16_printint.c \
  pcre16_refcount.c \
  pcre16_string_utils.c \
  pcre16_study.c \
  pcre16_tables.c \
  pcre16_ucd.c \
  pcre16_utf16_utils.c \
  pcre16_valid_utf16.c \
  pcre16_version.c \
  pcre16_xclass.c \
  pcre32_byte_order.c \
  pcre32_chartables.c \
  pcre32_compile.c \
  pcre32_config.c \
  pcre32_dfa_exec.c \
  pcre32_exec.c \
  pcre32_fullinfo.c \
  pcre32_get.c \
  pcre32_globals.c \
  pcre32_jit_compile.c \
  pcre32_maketables.c \
  pcre32_newline.c \
  pcre32_ord2utf32.c \
  pcre32_printint.c \
  pcre32_refcount.c \
  pcre32_string_utils.c \
  pcre32_study.c \
  pcre32_tables.c \
  pcre32_ucd.c \
  pcre32_utf32_utils.c \
  pcre32_valid_utf32.c \
  pcre32_version.c \
  pcre32_xclass.c \
  pcre_byte_order.c \
  pcre_chartables.c \
  pcre_compile.c \
  pcre_config.c \
  pcre_dfa_exec.c \
  pcre_exec.c \
  pcre_fullinfo.c \
  pcre_get.c \
  pcre_globals.c \
  pcre_jit_compile.c \
  pcre_maketables.c \
  pcre_newline.c \
  pcre_ord2utf8.c \
  pcre_printint.c \
  pcre_refcount.c \
  pcre_string_utils.c \
  pcre_study.c \
  pcre_tables.c \
  pcre_ucd.c \
  pcre_valid_utf8.c \
  pcre_version.c \
  pcre_xclass.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)

LOCAL_CFLAGS := -DHAVE_CONFIG_H -DHAVE_STDLIB_H -DHAVE_SYS_STAT_H -DHAVE_SYS_TYPES_H

include $(BUILD_SHARED_LIBRARY)

