--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefCOM


project( "gucefCOM" )
location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "ANDROID" } )
language( "C" )

configuration( { "LINUX" } )
language( "C" )

configuration( { "OSX" } )
language( "C" )

configuration( { "WIN32" } )
language( "C" )

configuration( { "WIN64" } )
language( "C" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT" } )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT" } )


configuration( {} )
defines( { "GUCEF_COM_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/CDBColumn.h",
  "include/CDBField.h",
  "include/CDBQuery.h",
  "include/CGUCEFCOMModule.h",
  "include/CHTTPClient.h",
  "include/CHTTPURLHandler.h",
  "include/CMySQLClient.h",
  "include/CMySQLClientInterface.h",
  "include/CPHUDPSocket.h",
  "include/gucefCOM.h",
  "include/gucefCOMDLLInit.h",
  "include/gucefCOM_CComGlobal.h",
  "include/gucefCOM_CDefaultHTTPServerRouterController.h",
  "include/gucefCOM_CHTTPServer.h",
  "include/gucefCOM_CIHTTPServerResource.h",
  "include/gucefCOM_CIHTTPServerRouter.h",
  "include/gucefCOM_CIHTTPServerRouterController.h",
  "include/gucefCOM_config.h",
  "include/gucefCOM_ETypes.h",
  "include/gucefCOM_HTTPCode.h",
  "include/gucefCOM_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/CDBQuery.cpp",
  "src/CGUCEFCOMModule.cpp",
  "src/CHTTPClient.cpp",
  "src/CHTTPURLHandler.cpp",
  "src/CMySQLClient.cpp",
  "src/CPHUDPSocket.cpp",
  "src/gucefCOM.cpp",
  "src/gucefCOM_CComGlobal.cpp",
  "src/gucefCOM_CDefaultHTTPServerRouterController.cpp",
  "src/gucefCOM_CHTTPServer.cpp",
  "src/gucefCOM_CIHTTPServerResource.cpp",
  "src/gucefCOM_CIHTTPServerRouter.cpp",
  "src/gucefCOM_CIHTTPServerRouterController.cpp"
 } )


configuration( {} )
includedirs( { "../common/include", "../gucefCOMCORE/include", "../gucefCORE/include", "../gucefMT/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../gucefCORE/include/android" } )

configuration( { "LINUX" } )
includedirs( { "../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../gucefCOMCORE/include/mswin", "../gucefCORE/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../gucefCOMCORE/include/mswin", "../gucefCORE/include/mswin" } )
