--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: libpng


project( "libpng" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "zlib" } )
links( { "zlib" } )


configuration( {} )
defines( { "PNG_NO_CONFIG_H", "PNG_USE_DLL" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "png.h",
  "pngconf.h",
  "pngdebug.h",
  "pnginfo.h",
  "pnglibconf.h",
  "pngpriv.h",
  "pngstruct.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "png.c",
  "pngerror.c",
  "pngget.c",
  "pngmem.c",
  "pngpread.c",
  "pngread.c",
  "pngrio.c",
  "pngrtran.c",
  "pngrutil.c",
  "pngset.c",
  "pngtrans.c",
  "pngwio.c",
  "pngwrite.c",
  "pngwtran.c",
  "pngwutil.c"
 } )


configuration( {} )

configuration( { "LINUX32" } )
includedirs( { "../zlib" } )

configuration( { "LINUX64" } )
includedirs( { "../zlib" } )

configuration( { "WIN32" } )
includedirs( { "../zlib" } )

configuration( { "WIN64" } )
includedirs( { "../zlib" } )
