CALL CMakeCommon.bat

ECHO *** Set CB NIX specifics and run CMake ***

SET E_OUTPUTDIR="%OUTPUTDIR%\ENIX"
CMake.exe -DBUILD_SHARED_LIBS=ON -G"Eclipse CDT4 - Unix Makefiles" -DECLIPSE_CDT4_GENERATE_SOURCE_PROJECT=TRUE -H"%SRCROOTDIR%" -B%E_OUTPUTDIR%
PAUSE