#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := gucefCOM
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/CDBQuery.cpp \
  src/CGUCEFCOMModule.cpp \
  src/CHTTPClient.cpp \
  src/CHTTPURLHandler.cpp \
  src/CMySQLClient.cpp \
  src/CPHUDPSocket.cpp \
  src/gucefCOM.cpp \
  src/gucefCOM_CDefaultHTTPServerRouterController.cpp \
  src/gucefCOM_CHTTPServer.cpp \
  src/gucefCOM_CIHTTPServerResource.cpp \
  src/gucefCOM_CIHTTPServerRouter.cpp \
  src/gucefCOM_CIHTTPServerRouterController.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../common/include \
  $(MY_MODULE_PATH)/../gucefCOMCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include/android \
  $(MY_MODULE_PATH)/../gucefMT/include

LOCAL_CFLAGS := -DGUCEF_COM_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  gucefCOMCORE \
  gucefMT \
  gucefCORE

include $(BUILD_SHARED_LIBRARY)

