--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefPUBSUB


project( "gucefPUBSUB" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCOM", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefVFS", "gucefWEB" } )
links( { "gucefCOM", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefVFS", "gucefWEB" } )


configuration( {} )
defines( { "GUCEF_PUBSUB_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/gucefPUBSUB.h",
  "include/gucefPUBSUB_CBasicPubSubMsg.h",
  "include/gucefPUBSUB_CBinaryPubSubJournal.h",
  "include/gucefPUBSUB_CIPubSubBookmarkPersistence.h",
  "include/gucefPUBSUB_CIPubSubJournal.h",
  "include/gucefPUBSUB_CIPubSubMsg.h",
  "include/gucefPUBSUB_CModule.h",
  "include/gucefPUBSUB_CPubSub2PubSub.h",
  "include/gucefPUBSUB_CPubSubBookmark.h",
  "include/gucefPUBSUB_CPubSubBookmarkBinarySerializer.h",
  "include/gucefPUBSUB_CPubSubBookmarkPersistenceFactory.h",
  "include/gucefPUBSUB_CPubSubChannelSettings.h",
  "include/gucefPUBSUB_CPubSubClient.h",
  "include/gucefPUBSUB_CPubSubClientChannel.h",
  "include/gucefPUBSUB_CPubSubClientConfig.h",
  "include/gucefPUBSUB_CPubSubClientFactory.h",
  "include/gucefPUBSUB_CPubSubClientFeatures.h",
  "include/gucefPUBSUB_CPubSubClientSide.h",
  "include/gucefPUBSUB_CPubSubClientTopic.h",
  "include/gucefPUBSUB_CPubSubClientTopicConfig.h",
  "include/gucefPUBSUB_CPubSubFlowRouteConfig.h",
  "include/gucefPUBSUB_CPubSubFlowRouter.h",
  "include/gucefPUBSUB_CPubSubFlowRouterConfig.h",
  "include/gucefPUBSUB_CPubSubGlobal.h",
  "include/gucefPUBSUB_CPubSubJournalConfig.h",
  "include/gucefPUBSUB_CPubSubJournalFactory.h",
  "include/gucefPUBSUB_CPubSubMsgBinarySerializer.h",
  "include/gucefPUBSUB_CPubSubMsgContainerBinarySerializer.h",
  "include/gucefPUBSUB_CPubSubMsgSerializer.h",
  "include/gucefPUBSUB_CPubSubSideChannelSettings.h",
  "include/gucefPUBSUB_CVfsPubSubBookmarkPersistence.h",
  "include/gucefPUBSUB_ETypes.h",
  "include/gucefPUBSUB_PubSubRouteTypes.h",
  "include/gucefPUBSUB_config.h",
  "include/gucefPUBSUB_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/gucefPUBSUB.cpp",
  "src/gucefPUBSUB_CBasicPubSubMsg.cpp",
  "src/gucefPUBSUB_CBinaryPubSubJournal.cpp",
  "src/gucefPUBSUB_CIPubSubBookmarkPersistence.cpp",
  "src/gucefPUBSUB_CIPubSubJournal.cpp",
  "src/gucefPUBSUB_CIPubSubMsg.cpp",
  "src/gucefPUBSUB_CModule.cpp",
  "src/gucefPUBSUB_CPubSub2PubSub.cpp",
  "src/gucefPUBSUB_CPubSubBookmark.cpp",
  "src/gucefPUBSUB_CPubSubBookmarkBinarySerializer.cpp",
  "src/gucefPUBSUB_CPubSubChannelSettings.cpp",
  "src/gucefPUBSUB_CPubSubClient.cpp",
  "src/gucefPUBSUB_CPubSubClientChannel.cpp",
  "src/gucefPUBSUB_CPubSubClientConfig.cpp",
  "src/gucefPUBSUB_CPubSubClientFactory.cpp",
  "src/gucefPUBSUB_CPubSubClientFeatures.cpp",
  "src/gucefPUBSUB_CPubSubClientSide.cpp",
  "src/gucefPUBSUB_CPubSubClientTopic.cpp",
  "src/gucefPUBSUB_CPubSubClientTopicConfig.cpp",
  "src/gucefPUBSUB_CPubSubFlowRouteConfig.cpp",
  "src/gucefPUBSUB_CPubSubFlowRouter.cpp",
  "src/gucefPUBSUB_CPubSubFlowRouterConfig.cpp",
  "src/gucefPUBSUB_CPubSubGlobal.cpp",
  "src/gucefPUBSUB_CPubSubJournalConfig.cpp",
  "src/gucefPUBSUB_CPubSubMsgBinarySerializer.cpp",
  "src/gucefPUBSUB_CPubSubMsgContainerBinarySerializer.cpp",
  "src/gucefPUBSUB_CPubSubMsgSerializer.cpp",
  "src/gucefPUBSUB_CPubSubSideChannelSettings.cpp",
  "src/gucefPUBSUB_CVfsPubSubBookmarkPersistence.cpp",
  "src/gucefPUBSUB_PubSubRouteTypes.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../gucefCOM/include", "../gucefCOMCORE/include", "../gucefCORE/include", "../gucefCORE/include/c_api", "../gucefMT/include", "../gucefVFS/include", "../gucefWEB/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../gucefCOMCORE/include/linux", "../gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../gucefCOMCORE/include/linux", "../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../gucefCOMCORE/include/mswin", "../gucefCORE/include/mswin", "../gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../gucefCOMCORE/include/mswin", "../gucefCORE/include/mswin", "../gucefMT/include/mswin" } )
