--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: guidriverCEGUIOpenGL


project( "guidriverCEGUIOpenGL" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "CEGUI", "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS", "guidriverCEGUI" } )
links( { "CEGUI", "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS", "guidriverCEGUI" } )


configuration( {} )
defines( { "GUCEF_GUIDRIVERCEGUIGL_BUILD_MODULE" } )
  
configuration( { ANDROID } )
links( { "CEGUI.RendererModule.OpenGLES" } )
  links( { "CEGUI.RendererModule.OpenGLES", "GLESv1_CM" } )
  
configuration( { LINUX32 } )
links( { "CEGUI.RendererModule.OpenGL" } )
  links( { "CEGUI.RendererModule.OpenGL", "GL" } )
  
configuration( { LINUX64 } )
links( { "CEGUI.RendererModule.OpenGL" } )
  links( { "CEGUI.RendererModule.OpenGL", "GL" } )
  
configuration( { WIN32 } )
links( { "CEGUI.RendererModule.OpenGL" } )
  links( { "CEGUI.RendererModule.OpenGL", "OpenGL32" } )
  
configuration( { WIN64 } )
links( { "CEGUI.RendererModule.OpenGL" } )
  links( { "CEGUI.RendererModule.OpenGL", "OpenGL32" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/guidriverCEGUIOpenGL.h",
  "include/guidriverCEGUIOpenGL_CGUIContextGL.h",
  "include/guidriverCEGUIOpenGL_CGUIDriverGL.h",
  "include/guidriverCEGUIOpenGL_config.h",
  "include/guidriverCEGUIOpenGL_macros.h",
  "include/guidriverCEGUIOpenGL_pluginAPI.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/guidriverCEGUIOpenGL.cpp",
  "src/guidriverCEGUIOpenGL_CGUIContextGL.cpp",
  "src/guidriverCEGUIOpenGL_CGUIDriverGL.cpp",
  "src/guidriverCEGUIOpenGL_pluginAPI.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/cegui/cegui/include", "../../../dependencies/freetype/include", "../../../dependencies/freetype/include/freetype", "../../../dependencies/freetype/include/freetype/config", "../../../dependencies/freetype/include/freetype/internal", "../../../dependencies/freetype/include/freetype/internal/services", "../../../dependencies/freetype/src", "../../../dependencies/freetype/src/winfonts", "../../../platform/gucefCORE/include", "../../../platform/gucefGUI/include", "../../../platform/gucefIMAGE/include", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include", "../../../platform/gucefVFS/include", "../guidriverCEGUI/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
