#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif

include $(CLEAR_VARS)

LOCAL_MODULE := gucefCOMCORE

LOCAL_SRC_FILES := \
  $(MY_MODULE_PATH)/src/CCom.cpp \
  $(MY_MODULE_PATH)/src/CGUCEFCOMCOREModule.cpp \
  $(MY_MODULE_PATH)/src/CHostAddress.cpp \
  $(MY_MODULE_PATH)/src/CIPAddress.cpp \
  $(MY_MODULE_PATH)/src/CPing.cpp \
  $(MY_MODULE_PATH)/src/CSocket.cpp \
  $(MY_MODULE_PATH)/src/CTCPClientSocket.cpp \
  $(MY_MODULE_PATH)/src/CTCPConnection.cpp \
  $(MY_MODULE_PATH)/src/CTCPServerConnection.cpp \
  $(MY_MODULE_PATH)/src/CTCPServerSocket.cpp \
  $(MY_MODULE_PATH)/src/CUDPChannel.cpp \
  $(MY_MODULE_PATH)/src/CUDPMasterSocket.cpp \
  $(MY_MODULE_PATH)/src/CUDPSocket.cpp \
  $(MY_MODULE_PATH)/src/dvwinsock.c \
  $(MY_MODULE_PATH)/src/gucefCOMCORE.cpp \
  $(MY_MODULE_PATH)/src/socketutils.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../gucefCORE/include \
  $(MY_MODULE_PATH)/../gucefMT/include


LOCAL_SHARED_LIBRARIES := \
  gucefMT \
  gucefCORE

include $(BUILD_SHARED_LIBRARY)

