#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := CEGUI.RendererModule.Ogre
LOCAL_MODULE_FILENAME := libCEGUI.RendererModule.Ogre
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  GeometryBuffer.cpp \
  ImageCodec.cpp \
  Renderer.cpp \
  ResourceProvider.cpp \
  Texture.cpp \
  TextureTarget.cpp \
  WindowTarget.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/include \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/include/Android \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/include/Hash \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/include/Threading \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/src \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/src/nedmalloc \
  $(MY_MODULE_PATH)/../../../../../Ogre/OgreMain/src/stbi \
  $(MY_MODULE_PATH)/../../../../../Ogre/include \
  $(MY_MODULE_PATH)/../../../../../freetype/include \
  $(MY_MODULE_PATH)/../../../../../freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../../../freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../../../freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../../../freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../../../freetype/src \
  $(MY_MODULE_PATH)/../../../../../freetype/src/winfonts \
  $(MY_MODULE_PATH)/../../../include

LOCAL_CFLAGS := -DCEGUIOGRERENDERER_EXPORTS


LOCAL_SHARED_LIBRARIES := \
  CEGUI \
  Ogre

include $(BUILD_SHARED_LIBRARY)

