--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_udp2redis" )

  platforms( { "ALL" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "dependencies/hiredis" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libparsifal" )
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "tools/udp2redis" )
