// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type GucefCoreDynamic struct {
	LenData uint32
	Data []byte
	_io *kaitai.Stream
	_root *GucefCoreDynamic
	_parent interface{}
}
func NewGucefCoreDynamic() *GucefCoreDynamic {
	return &GucefCoreDynamic{
	}
}

func (this *GucefCoreDynamic) Read(io *kaitai.Stream, parent interface{}, root *GucefCoreDynamic) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenData = uint32(tmp1)
	tmp2, err := this._io.ReadBytes(int(this.LenData))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Data = tmp2
	return err
}
