// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)

type GucefPubsubMsgcontainer struct {
	Header *GucefPubsubMsgcontainerHeader
	Pubsubmsg []*GucefPubsubMsgcontainer_GucefPubsubMsg
	Footer *GucefPubsubMsgcontainerFooter
	_io *kaitai.Stream
	_root *GucefPubsubMsgcontainer
	_parent interface{}
	_f_msgOffsetIdxSize bool
	msgOffsetIdxSize uint32
}
func NewGucefPubsubMsgcontainer() *GucefPubsubMsgcontainer {
	return &GucefPubsubMsgcontainer{
	}
}

func (this *GucefPubsubMsgcontainer) Read(io *kaitai.Stream, parent interface{}, root *GucefPubsubMsgcontainer) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGucefPubsubMsgcontainerHeader()
	err = tmp1.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Header = tmp1
	for i := 1;; i++ {
		tmp2 := NewGucefPubsubMsgcontainer_GucefPubsubMsg()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp2
		this.Pubsubmsg = append(this.Pubsubmsg, _it)
		tmp3, err := this._io.Pos()
		if err != nil {
			return err
		}
		tmp4, err := this._io.Size()
		if err != nil {
			return err
		}
		tmp5, err := this.MsgOffsetIdxSize()
		if err != nil {
			return err
		}
		if tmp3 == (((tmp4 - (tmp5 * 4)) - 4) - 10) {
			break
		}
	}
	tmp6 := NewGucefPubsubMsgcontainerFooter()
	err = tmp6.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Footer = tmp6
	return err
}
func (this *GucefPubsubMsgcontainer) MsgOffsetIdxSize() (v uint32, err error) {
	if (this._f_msgOffsetIdxSize) {
		return this.msgOffsetIdxSize, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return 0, err
	}
	tmp7, err := this._io.Size()
	if err != nil {
		return 0, err
	}
	_, err = this._io.Seek(int64((tmp7 - 14)), io.SeekStart)
	if err != nil {
		return 0, err
	}
	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return 0, err
	}
	this.msgOffsetIdxSize = tmp8
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return 0, err
	}
	this._f_msgOffsetIdxSize = true
	this._f_msgOffsetIdxSize = true
	return this.msgOffsetIdxSize, nil
}
type GucefPubsubMsgcontainer_GucefPubsubMsg struct {
	MsgDateTime uint64
	Msgid *GucefCoreVariant
	MsgIndex *GucefCoreVariant
	PrimaryPayloadIncluded *GucefCoreVariant
	NrOfKvPairs uint32
	KeyValuePairs []*GucefPubsubMsgcontainer_KvPair
	NrOfMetadataKvPairs uint32
	MetadataKeyValuePairs []*GucefPubsubMsgcontainer_KvPair
	_io *kaitai.Stream
	_root *GucefPubsubMsgcontainer
	_parent *GucefPubsubMsgcontainer
}
func NewGucefPubsubMsgcontainer_GucefPubsubMsg() *GucefPubsubMsgcontainer_GucefPubsubMsg {
	return &GucefPubsubMsgcontainer_GucefPubsubMsg{
	}
}

func (this *GucefPubsubMsgcontainer_GucefPubsubMsg) Read(io *kaitai.Stream, parent *GucefPubsubMsgcontainer, root *GucefPubsubMsgcontainer) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	if ((this._root.Header.Options & (1 << 1)) != 0) {
		switch ((this._root.Header.Options & (1 << 2))) {
		case 0:
			tmp9, err := this._io.ReadU4le()
			if err != nil {
				return err
			}
			this.MsgDateTime = uint64(tmp9)
		default:
			tmp10, err := this._io.ReadU8le()
			if err != nil {
				return err
			}
			this.MsgDateTime = uint64(tmp10)
		}
	}
	if ((this._root.Header.Options & (1 << 3)) != 0) {
		tmp11 := NewGucefCoreVariant()
		err = tmp11.Read(this._io, this, nil)
		if err != nil {
			return err
		}
		this.Msgid = tmp11
	}
	if ((this._root.Header.Options & (1 << 4)) != 0) {
		tmp12 := NewGucefCoreVariant()
		err = tmp12.Read(this._io, this, nil)
		if err != nil {
			return err
		}
		this.MsgIndex = tmp12
	}
	if ((this._root.Header.Options & (1 << 5)) != 0) {
		tmp13 := NewGucefCoreVariant()
		err = tmp13.Read(this._io, this, nil)
		if err != nil {
			return err
		}
		this.PrimaryPayloadIncluded = tmp13
	}
	if ((this._root.Header.Options & (1 << 6)) != 0) {
		tmp14, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NrOfKvPairs = uint32(tmp14)
	}
	if ((this._root.Header.Options & (1 << 6)) != 0) {
		for i := 0; i < int(this.NrOfKvPairs); i++ {
			_ = i
			tmp15 := NewGucefPubsubMsgcontainer_KvPair()
			err = tmp15.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.KeyValuePairs = append(this.KeyValuePairs, tmp15)
		}
	}
	if ((this._root.Header.Options & (1 << 7)) != 0) {
		tmp16, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.NrOfMetadataKvPairs = uint32(tmp16)
	}
	if ((this._root.Header.Options & (1 << 7)) != 0) {
		for i := 0; i < int(this.NrOfMetadataKvPairs); i++ {
			_ = i
			tmp17 := NewGucefPubsubMsgcontainer_KvPair()
			err = tmp17.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.MetadataKeyValuePairs = append(this.MetadataKeyValuePairs, tmp17)
		}
	}
	return err
}
type GucefPubsubMsgcontainer_KvPair struct {
	Key *GucefCoreVariant
	Value *GucefCoreVariant
	_io *kaitai.Stream
	_root *GucefPubsubMsgcontainer
	_parent *GucefPubsubMsgcontainer_GucefPubsubMsg
}
func NewGucefPubsubMsgcontainer_KvPair() *GucefPubsubMsgcontainer_KvPair {
	return &GucefPubsubMsgcontainer_KvPair{
	}
}

func (this *GucefPubsubMsgcontainer_KvPair) Read(io *kaitai.Stream, parent *GucefPubsubMsgcontainer_GucefPubsubMsg, root *GucefPubsubMsgcontainer) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp18 := NewGucefCoreVariant()
	err = tmp18.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Key = tmp18
	tmp19 := NewGucefCoreVariant()
	err = tmp19.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Value = tmp19
	return err
}
