--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: guidriverWin32D3D9


configuration( { "WIN32" } )
  project( "guidriverWin32D3D9" )

configuration( { "WIN64" } )
  project( "guidriverWin32D3D9" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )
  
configuration( { WIN32 } )
links( { "Direct3D9", "gucefCORE", "gucefGUI", "gucefMT" } )
  links( { "d3d9", "d3dx9", "gucefCORE", "gucefGUI", "gucefMT" } )
  

configuration( { WIN32 } )
defines( { "GUIDRIVERWIN32D3D9_BUILD_MODULE" } )
  
configuration( { WIN64 } )
links( { "Direct3D9", "gucefCORE", "gucefGUI", "gucefMT" } )
  links( { "d3d9", "d3dx9", "gucefCORE", "gucefGUI", "gucefMT" } )
  

configuration( { WIN64 } )
defines( { "GUIDRIVERWIN32D3D9_BUILD_MODULE" } )


configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/guidriverWin32D3D9.h",
      "include/guidriverWin32D3D9_CWin32D3D9WindowContext.h",
      "include/guidriverWin32D3D9_CWin32D3D9WindowManagerImp.h",
      "include/guidriverWin32D3D9_config.h",
      "include/guidriverWin32D3D9_macros.h",
      "include/guidriverWin32D3D9_pluginAPI.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/guidriverWin32D3D9_CWin32D3D9WindowContext.cpp",
      "src/guidriverWin32D3D9_CWin32D3D9WindowManagerImp.cpp",
      "src/guidriverWin32D3D9_pluginAPI.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/guidriverWin32D3D9.h",
      "include/guidriverWin32D3D9_CWin32D3D9WindowContext.h",
      "include/guidriverWin32D3D9_CWin32D3D9WindowManagerImp.h",
      "include/guidriverWin32D3D9_config.h",
      "include/guidriverWin32D3D9_macros.h",
      "include/guidriverWin32D3D9_pluginAPI.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/guidriverWin32D3D9_CWin32D3D9WindowContext.cpp",
      "src/guidriverWin32D3D9_CWin32D3D9WindowManagerImp.cpp",
      "src/guidriverWin32D3D9_pluginAPI.cpp"
    } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCORE/include", "../../../platform/gucefGUI/include", "../../../platform/gucefIMAGE/include", "../../../platform/gucefMT/include", "../../../platform/gucefVFS/include" } )

configuration( { "WIN32" } )
includedirs( { "#$#ENVVAR:DXSDK_DIR#$#/Include", "../../../dependencies/external", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin", "include" } )

configuration( { "WIN64" } )
includedirs( { "#$#ENVVAR:DXSDK_DIR#$#/Include", "../../../dependencies/external", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin", "include" } )
