--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_ArchiveDiff" )

  platforms( { "ALL", "LINUX32", "LINUX64", "WIN32", "WIN64" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "tools/ArchiveDiff" )

filter "LINUX32"
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "platform/gucefPATCHER" )
  include( "tools/ArchiveDiff" )
  include( "tools/ArchiveDiffLib" )

filter "LINUX64"
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "platform/gucefPATCHER" )
  include( "tools/ArchiveDiff" )
  include( "tools/ArchiveDiffLib" )

filter "WIN32"
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "platform/gucefPATCHER" )
  include( "tools/ArchiveDiff" )
  include( "tools/ArchiveDiffLib" )

filter "WIN64"
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "platform/gucefPATCHER" )
  include( "tools/ArchiveDiff" )
  include( "tools/ArchiveDiffLib" )
