#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := guidriverMyGUIOgre
LOCAL_MODULE_FILENAME := libguidriverMyGUIOgre
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/guidriverMyGUIOgre.cpp \
  src/guidriverMyGUIOgre_CGUIContextOgre.cpp \
  src/guidriverMyGUIOgre_CGUIDriverOgre.cpp \
  src/guidriverMyGUIOgre_CImageLoader.cpp \
  src/guidriverMyGUIOgre_pluginAPI.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../../../common/include \
  $(MY_MODULE_PATH)/../../../dependencies/MyGui/MyGUIEngine/include \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/include \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/include/Android \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/include/Hash \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/include/Threading \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/src \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/src/nedmalloc \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/OgreMain/src/stbi \
  $(MY_MODULE_PATH)/../../../dependencies/Ogre/include \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/src \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/src/winfonts \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include/android \
  $(MY_MODULE_PATH)/../../../platform/gucefGUI/include \
  $(MY_MODULE_PATH)/../../../platform/gucefIMAGE/include \
  $(MY_MODULE_PATH)/../../../platform/gucefINPUT/include \
  $(MY_MODULE_PATH)/../../../platform/gucefMT/include \
  $(MY_MODULE_PATH)/../../../platform/gucefVFS/include \
  $(MY_MODULE_PATH)/../guidriverMyGUI/include

LOCAL_CFLAGS := -DGUIDRIVERMYGUIOGRE_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  MyGUI.Engine \
  Ogre \
  freetype \
  gucefCORE \
  gucefGUI \
  gucefIMAGE \
  gucefINPUT \
  gucefMT \
  gucefVFS \
  guidriverMyGUI


LOCAL_LDLIBS := \
  -lMyGUI.OgrePlatform

include $(BUILD_SHARED_LIBRARY)

