#!/bin/sh
# Generated for Agar by BSDBuild 3.2.
# <http://bsdbuild.hypertriton.com>

prefix="/usr/local"
exec_prefix="/usr/local"
exec_prefix_set="no"
libdir="/usr/local/lib"

usage="Usage: agar-au-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"

if test $# -eq 0; then
	echo "${usage}" 1>&2
	exit 1
fi

while test $# -gt 0; do
	case "$1" in
	-*=*)
		optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'`
		;;
	*)
		optarg=
		;;
	esac

	case $1 in
	--prefix=*)
		prefix=$optarg
		if test $exec_prefix_set = no ; then
			exec_prefix=$optarg
		fi
		;;
	--prefix)
		echo "$prefix"
		;;
	--exec-prefix=*)
		exec_prefix=$optarg
		exec_prefix_set=yes
		;;
	--exec-prefix)
		echo "$exec_prefix"
		;;
	--version)
		echo "1.5.0"
		;;
	--cflags)
		echo "-I/usr/local/include/agar  "
		;;
	--libs | --static-libs)
		echo "-L/usr/local/lib -lag_au  "
		;;
	*)
		echo "${usage}" 1>&2
		exit 1
		;;
	esac
	shift
done
