--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefCOMCORE

project( "gucefCOMCORE" )
location( os.getenv( "PM4OUTPUTDIR" ) )
kind( "SharedLib" )
links( { "gucefCORE", "gucefMT" } )
links( { "gucefCORE", "gucefMT" } )
defines( { "GUCEF_COMCORE_BUILD_MODULE" } )

configuration( { "WIN32" } )
  links( { "Advapi32.lib", "Ws2_32.lib" } )

configuration( { "WIN64" } )
  links( { "Advapi32.lib", "Ws2_32.lib" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/CCom.h",
  "include/CGUCEFCOMCOREModule.h",
  "include/CHostAddress.h",
  "include/CIPAddress.h",
  "include/CPing.h",
  "include/CSocket.h",
  "include/CTCPClientSocket.h",
  "include/CTCPConnection.h",
  "include/CTCPServerConnection.h",
  "include/CTCPServerSocket.h",
  "include/CUDPChannel.h",
  "include/CUDPMasterSocket.h",
  "include/CUDPSocket.h",
  "include/dvwinsock.h",
  "include/gucefCOMCORE.h",
  "include/gucefCOMCORE_CComCoreGlobal.h",
  "include/gucefCOMCORE_CICommunicationPort.h",
  "include/gucefCOMCORE_config.h",
  "include/gucefCOMCORE_CPingTaskConsumer.h",
  "include/gucefCOMCORE_CSerialPort.h",
  "include/gucefCOMCORE_ETypes.h",
  "include/gucefCOMCORE_macros.h",
  "include/socketerrors.h",
  "include/socketutils.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/CCom.cpp",
  "src/CGUCEFCOMCOREModule.cpp",
  "src/CHostAddress.cpp",
  "src/CIPAddress.cpp",
  "src/CPing.cpp",
  "src/CSocket.cpp",
  "src/CTCPClientSocket.cpp",
  "src/CTCPConnection.cpp",
  "src/CTCPServerConnection.cpp",
  "src/CTCPServerSocket.cpp",
  "src/CUDPChannel.cpp",
  "src/CUDPMasterSocket.cpp",
  "src/CUDPSocket.cpp",
  "src/dvwinsock.c",
  "src/gucefCOMCORE.cpp",
  "src/gucefCOMCORE_CComCoreGlobal.cpp",
  "src/gucefCOMCORE_CICommunicationPort.cpp",
  "src/gucefCOMCORE_CPingTaskConsumer.cpp",
  "src/gucefCOMCORE_CSerialPort.cpp",
  "src/socketutils.cpp"
 } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include\mswin\gucefCOMCORE_CWin32SerialPort.h",
      "include\mswin\gucefCOMCORE_icmpApi.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src\mswin\gucefCOMCORE_CWin32SerialPort.cpp",
      "src\mswin\gucefCOMCORE_icmpApi.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include\mswin\gucefCOMCORE_CWin32SerialPort.h",
      "include\mswin\gucefCOMCORE_icmpApi.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src\mswin\gucefCOMCORE_CWin32SerialPort.cpp",
      "src\mswin\gucefCOMCORE_icmpApi.cpp"
    } )


configuration( {} )
includedirs( { "../common/include", "../gucefCORE/include", "../gucefMT/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../gucefCORE/include/android" } )

configuration( { "LINUX" } )
includedirs( { "../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../gucefCORE/include/mswin", "include\mswin" } )

configuration( { "WIN64" } )
includedirs( { "../gucefCORE/include/mswin", "include\mswin" } )
