@echo off

SET FINDGUCEFHOME_THEBATCHDIR=%~dp0

ECHO.
ECHO *** Locating GUCEF_HOME ***
ECHO.

IF NOT DEFINED GUCEF_HOME (
  ECHO GUCEF environment variable not found, setting it
  SET GUCEF_HOME=%FINDGUCEFHOME_THEBATCHDIR%..\..
  SET MSWIN_GUCEF_HOME=%GUCEF_HOME%
)
ECHO GUCEF_HOME value is: %GUCEF_HOME%
