--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefGUI_TestApp


configuration( { "LINUX" } )
  project( "gucefGUI_TestApp" )

configuration( { "WIN32" } )
  project( "gucefGUI_TestApp" )

configuration( { "WIN64" } )
  project( "gucefGUI_TestApp" )
location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "LINUX" } )
kind( "ConsoleApp" )
configuration( { "WIN32" } )
kind( "WindowedApp" )
configuration( { "WIN64" } )
kind( "WindowedApp" )

configuration( { "LINUX" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )

configuration( { "WIN32" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )

configuration( { "WIN64" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  links( { "gucefCORE", "gucefGUI", "gucefIMAGE", "gucefINPUT", "gucefMT", "gucefVFS" } )
  defines( { "GUCEF_GUI_TESTAPP_BUILD_MODULE" } )


configuration( { "LINUX" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/gucefGUI_TestApp.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../gucefCORE/include", "../../gucefGUI/include", "../../gucefIMAGE/include", "../../gucefINPUT/include", "../../gucefMT/include", "../../gucefVFS/include" } )

configuration( { "LINUX" } )
includedirs( { "../../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../gucefCORE/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../gucefCORE/include/mswin" } )
