#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


#
# This is the project makefile which includes all modules which are part of this project
#
# PROJECT: "GUCEF"
#

PROJECT_REDIRECT_ROOT_PATH := $(call my-dir)

include $(CLEAR_VARS)

PROJECT_ROOT_PATH := $(PROJECT_REDIRECT_ROOT_PATH)/../../..
include $(PROJECT_ROOT_PATH)/Android.mk
