--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: dstorepluginJSONPARSER


project( "dstorepluginJSONPARSER" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "jsonbuilder", "jsonparser" } )
links( { "jsonbuilder", "jsonparser" } )


configuration( {} )
defines( { "DSTOREPLUGINJSONPARSER_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainDSTOREpluginJSONPARSER.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainDSTOREpluginJSONPARSER.c"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/android" } )

configuration( { "ARDUINO" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "EMSCRIPTEN" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "GLX" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "GTK" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "IOS" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/linux" } )

configuration( { "NACL" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "OSX" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "POSIX" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "SDL" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "SYMBIAN" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "UNIX" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
