#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := gucefPATCHER
LOCAL_MODULE_FILENAME := gucefPATCHER
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/gucefPATCHER.cpp \
  src/gucefPATCHER_CModule.cpp \
  src/gucefPATCHER_CPatchConfig.cpp \
  src/gucefPATCHER_CPatchEngine.cpp \
  src/gucefPATCHER_CPatchListEngine.cpp \
  src/gucefPATCHER_CPatchListEngineEvents.cpp \
  src/gucefPATCHER_CPatchListParser.cpp \
  src/gucefPATCHER_CPatchManager.cpp \
  src/gucefPATCHER_CPatchSetDirEngine.cpp \
  src/gucefPATCHER_CPatchSetDirEngineEvents.cpp \
  src/gucefPATCHER_CPatchSetEngine.cpp \
  src/gucefPATCHER_CPatchSetEngineEvents.cpp \
  src/gucefPATCHER_CPatchSetFileEngine.cpp \
  src/gucefPATCHER_CPatchSetFileEngineEvents.cpp \
  src/gucefPATCHER_CPatchSetGenerator.cpp \
  src/gucefPATCHER_CPatchSetParser.cpp \
  src/gucefPATCHER_CPatchTaskConsumer.cpp \
  src/gucefPATCHER_CPatchTaskData.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../common/include \
  $(MY_MODULE_PATH)/../gucefCOM/include \
  $(MY_MODULE_PATH)/../gucefCOMCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include/android \
  $(MY_MODULE_PATH)/../gucefMT/include


LOCAL_SHARED_LIBRARIES := \
  gucefCOM \
  gucefCOMCORE \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

