--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefPRODMANAPP

project( "gucefPRODMANAPP" )
location( os.getenv( "PM4OUTPUTDIR" ) )
kind( "SharedLib" )
links( { "gucefCOM" "gucefCOMCORE" "gucefCORE" "gucefMT" "gucefPRODMAN" } )
links( { "gucefCOM" "gucefCOMCORE" "gucefCORE" "gucefMT" "gucefPRODMAN" } )
defines( { "GUCEF_PRODMANAPP_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/gucefPRODMANAPP_config.h",
  "include/gucefPRODMANAPP_macros.h",
  "include/gucefPRODMANAPP_main.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/gucefPRODMANAPP_main.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../../gucefCOM/include", "../../gucefCOMCORE/include", "../../gucefCORE/include", "../../gucefMT/include", "../../gucefPATCHER/include", "../../gucefPRODMAN/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../../gucefCORE/include/android" } )

configuration( { "LINUX" } )
includedirs( { "../../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../gucefCOMCORE/include/mswin", "../../gucefCORE/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../gucefCOMCORE/include/mswin", "../../gucefCORE/include/mswin" } )
