#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := gucefDRN

LOCAL_SRC_FILES := \
  $(LOCAL_PATH)/src/gucefDRN.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNDataGroup.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNDataGroupProperties.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNDataStream.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNNode.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNPeerLink.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CDRNPeerLinkData.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CGUCEFDRNModule.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CIDRNPeerLinkCrypter.cpp \
  $(LOCAL_PATH)/src/gucefDRN_CIDRNPeerValidator.cpp

LOCAL_C_INCLUDES := \
  $(LOCAL_PATH)/include \
  $(LOCAL_PATH)/../gucefCOM/include \
  $(LOCAL_PATH)/../gucefCOMCORE/include \
  $(LOCAL_PATH)/../gucefCORE/include \
  $(LOCAL_PATH)/../gucefMT/include


LOCAL_SHARED_LIBRARIES := \
  gucefCOM \
  gucefCOMCORE \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

