#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := aws-checksums
LOCAL_MODULE_FILENAME := libaws-checksums
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  source/cpuid_generic.c \
  source/crc.c \
  source/crc_jni.c \
  source/crc_sw.c \
  source/arm/cpuid_arm.c \
  source/arm/crc32c_arm.c \
  source/intel/cpuid.c \
  source/intel/crc32c_sse42_asm.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include/aws/checksums \
  $(MY_MODULE_PATH)/include/aws/checksums/private \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/aws

include $(BUILD_STATIC_LIBRARY)

