#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := gucefCORE
LOCAL_MODULE_FILENAME := libgucefCORE
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/CBlockStack.cpp \
  src/CCPPWrapFileAccess.cpp \
  src/CCodecChain.cpp \
  src/CCodecRegistry.cpp \
  src/CConfigStore.cpp \
  src/CCyclicDynamicBuffer.cpp \
  src/CDStoreCodec.cpp \
  src/CDStoreCodecPlugin.cpp \
  src/CDStoreCodecPluginManager.cpp \
  src/CDStoreCodecRegistry.cpp \
  src/CDataNode.cpp \
  src/CDataQueue.cpp \
  src/CDynamicBuffer.cpp \
  src/CDynamicBufferAccess.cpp \
  src/CEvent.cpp \
  src/CException.cpp \
  src/CExclusiveActivationManager.cpp \
  src/CExclusiveActiveObj.cpp \
  src/CFileAccess.cpp \
  src/CFileURLHandler.cpp \
  src/CGUCEFApplication.cpp \
  src/CGUCEFCOREModule.cpp \
  src/CGenericPlugin.cpp \
  src/CGenericPluginManager.cpp \
  src/CICloneable.cpp \
  src/CICodec.cpp \
  src/CICodecPlugin.cpp \
  src/CILogger.cpp \
  src/CINamedInstance.cpp \
  src/CINumericIDGeneratorBase.cpp \
  src/CIOAccess.cpp \
  src/CIPlugin.cpp \
  src/CIStreamable.cpp \
  src/CITypeNamed.cpp \
  src/CIURLEvents.cpp \
  src/CLLNode.cpp \
  src/CLogManager.cpp \
  src/CMFileAccess.cpp \
  src/CMachineState.cpp \
  src/CMemoryBlockPool.cpp \
  src/CMsgException.cpp \
  src/CNode.cpp \
  src/CNotificationIDRegistry.cpp \
  src/CNotifier.cpp \
  src/CNotifierImplementor.cpp \
  src/CNotifierObservingComponent.cpp \
  src/CNotifyingMapEvents.cpp \
  src/CObserver.cpp \
  src/CObservingNotifier.cpp \
  src/CPFileAccess.cpp \
  src/CPFileChunkAccess.cpp \
  src/CPluginControl.cpp \
  src/CPluginManager.cpp \
  src/CPumpedObserver.cpp \
  src/CROIOAccess.cpp \
  src/CSTDOStreamAdapter.cpp \
  src/CStack.cpp \
  src/CStateHandler.cpp \
  src/CStateMachine.cpp \
  src/CStateMachineComponent.cpp \
  src/CStdCodecPlugin.cpp \
  src/CStdCodecPluginItem.cpp \
  src/CStdCodecPluginManager.cpp \
  src/CStdLogger.cpp \
  src/CStreamerEvents.cpp \
  src/CSysConsole.cpp \
  src/CSysConsoleClient.cpp \
  src/CTAbstractFactory.cpp \
  src/CTAbstractFactoryWithParam.cpp \
  src/CTBasicSharedPtr.cpp \
  src/CTCloneableObj.cpp \
  src/CTCodecPluginItem.cpp \
  src/CTDynamicDestructor.cpp \
  src/CTDynamicDestructorBase.cpp \
  src/CTFactory.cpp \
  src/CTFactoryBase.cpp \
  src/CTFactoryBaseWithParam.cpp \
  src/CTFactoryWithParam.cpp \
  src/CTLinkedCloneableObj.cpp \
  src/CTNotifyingMap.cpp \
  src/CTNumericID.cpp \
  src/CTNumericIDGenerator.cpp \
  src/CTONRegistry.cpp \
  src/CTObservingNotifierComponent.cpp \
  src/CTObservingNotifierExpansion.cpp \
  src/CTRegistry.cpp \
  src/CTSGNotifier.cpp \
  src/CTSGObserver.cpp \
  src/CTSharedPtr.cpp \
  src/CTSingleton.cpp \
  src/CTimer.cpp \
  src/CTransactionEventControl.cpp \
  src/CURL.cpp \
  src/CURLDataRetriever.cpp \
  src/CURLHandler.cpp \
  src/CURLHandlerRegistry.cpp \
  src/CValueList.cpp \
  src/DVCPPOSWRAP.cpp \
  src/DVOSWRAP.cpp \
  src/IOACCESS.c \
  src/MFILE.c \
  src/MemoryPool.cpp \
  src/MemorySegment.cpp \
  src/PAFILE.c \
  src/cloneables.cpp \
  src/dvcppfileutils.cpp \
  src/dvcppstringutils.cpp \
  src/dvfileutils.cpp \
  src/dvmd5utils.c \
  src/dvstrutils.cpp \
  src/gucefCORE.cpp \
  src/gucefCORE_CAbstractFactoryBase.cpp \
  src/gucefCORE_CAsciiString.cpp \
  src/gucefCORE_CBasicBracketLoggingFormatter.cpp \
  src/gucefCORE_CBusyWaitPulseGeneratorDriver.cpp \
  src/gucefCORE_CCharSepLoggingFormatter.cpp \
  src/gucefCORE_CCoreGlobal.cpp \
  src/gucefCORE_CDStoreBinaryCodec.cpp \
  src/gucefCORE_CDataNodeBinarySerializer.cpp \
  src/gucefCORE_CDataNodeDefinition.cpp \
  src/gucefCORE_CDataNodeSerializableDataNode.cpp \
  src/gucefCORE_CDataNodeSerializableSettings.cpp \
  src/gucefCORE_CDate.cpp \
  src/gucefCORE_CDateTime.cpp \
  src/gucefCORE_CDirectoryWatcherEvents.cpp \
  src/gucefCORE_CDynamicBufferStringStream.cpp \
  src/gucefCORE_CDynamicBufferSwap.cpp \
  src/gucefCORE_CEnumerator.cpp \
  src/gucefCORE_CFileSystemDirectoryWatcher.cpp \
  src/gucefCORE_CFileSystemUriResourceAccessor.cpp \
  src/gucefCORE_CForwardingNotifier.cpp \
  src/gucefCORE_CFunctionRegistry.cpp \
  src/gucefCORE_CGenericValueToDataNodeSerializer.cpp \
  src/gucefCORE_CGlobalConfigValueList.cpp \
  src/gucefCORE_CGloballyConfigurable.cpp \
  src/gucefCORE_CIConfigurable.cpp \
  src/gucefCORE_CIConsoleLogger.cpp \
  src/gucefCORE_CIDataNodeSerializable.cpp \
  src/gucefCORE_CIDataNodeSerializableTaskData.cpp \
  src/gucefCORE_CIDate.cpp \
  src/gucefCORE_CIDirectoryWatcher.cpp \
  src/gucefCORE_CIEnumerable.cpp \
  src/gucefCORE_CIEventHandlerFunctorBase.cpp \
  src/gucefCORE_CIFunction.cpp \
  src/gucefCORE_CILoggingFormatter.cpp \
  src/gucefCORE_CIMetricsSystemClient.cpp \
  src/gucefCORE_CINotifier.cpp \
  src/gucefCORE_CIObserver.cpp \
  src/gucefCORE_CIPluginLoadLogic.cpp \
  src/gucefCORE_CIPluginMetaData.cpp \
  src/gucefCORE_CIPulseGeneratorDriver.cpp \
  src/gucefCORE_CITaskConsumer.cpp \
  src/gucefCORE_CITime.cpp \
  src/gucefCORE_CIValueToDataNodeSerializer.cpp \
  src/gucefCORE_CIniDataStoreCodec.cpp \
  src/gucefCORE_CIniParser.cpp \
  src/gucefCORE_CJsonLoggingFormatter.cpp \
  src/gucefCORE_CLinkedTransferBuffer.cpp \
  src/gucefCORE_CLoaderDelegatedPluginLoadLogic.cpp \
  src/gucefCORE_CLoggingGlobal.cpp \
  src/gucefCORE_CLoggingTask.cpp \
  src/gucefCORE_CMetricsClientManager.cpp \
  src/gucefCORE_CMultiLogger.cpp \
  src/gucefCORE_COSWindow.cpp \
  src/gucefCORE_CObserverSwitch.cpp \
  src/gucefCORE_CPlatformNativeConsoleLogger.cpp \
  src/gucefCORE_CPlatformNativeConsoleWindow.cpp \
  src/gucefCORE_CPluginGroup.cpp \
  src/gucefCORE_CPluginMetaData.cpp \
  src/gucefCORE_CProperty.cpp \
  src/gucefCORE_CPropertyDefinition.cpp \
  src/gucefCORE_CPropertyDefinitionList.cpp \
  src/gucefCORE_CPropertyList.cpp \
  src/gucefCORE_CPulseData.cpp \
  src/gucefCORE_CPulseGenerator.cpp \
  src/gucefCORE_CResourceMetaData.cpp \
  src/gucefCORE_CRollingFileAccess.cpp \
  src/gucefCORE_CSimplisticPluginLoadLogic.cpp \
  src/gucefCORE_CSingleTaskDelegator.cpp \
  src/gucefCORE_CStdDataNodeSerializableTaskData.cpp \
  src/gucefCORE_CSubFileAccess.cpp \
  src/gucefCORE_CTEventHandlerFunctor.cpp \
  src/gucefCORE_CTEventHandlerFunctorProxy.cpp \
  src/gucefCORE_CTIOAccessToStlStream.cpp \
  src/gucefCORE_CTIOAccessToStlStreambuff.cpp \
  src/gucefCORE_CTMultiRegistry.cpp \
  src/gucefCORE_CTaskDelegator.cpp \
  src/gucefCORE_CTaskInfo.cpp \
  src/gucefCORE_CTaskManager.cpp \
  src/gucefCORE_CTaskManagerInfo.cpp \
  src/gucefCORE_CThreadPool.cpp \
  src/gucefCORE_CThreadPoollnfo.cpp \
  src/gucefCORE_CThreadlnfo.cpp \
  src/gucefCORE_CTime.cpp \
  src/gucefCORE_CUri.cpp \
  src/gucefCORE_CUriResourceAccessor.cpp \
  src/gucefCORE_CUriResourceAccessorFactory.cpp \
  src/gucefCORE_CUrlEncoder.cpp \
  src/gucefCORE_CUtf8String.cpp \
  src/gucefCORE_CValueConstraint.cpp \
  src/gucefCORE_CValueConstraintList.cpp \
  src/gucefCORE_CValueDefinition.cpp \
  src/gucefCORE_CVariant.cpp \
  src/gucefCORE_CVariantBinarySerializer.cpp \
  src/gucefCORE_CVersion.cpp \
  src/gucefCORE_CVersionRange.cpp \
  src/gucefCORE_CoreCodecTypes.cpp \
  src/gucefCORE_LogLevels.cpp \
  src/gucefCORE_TaskStatus.cpp \
  src/gucefCORE_ThreadStatus.cpp \
  src/gucefCORE_VariantData.c \
  src/gucefCORE_cinterface.cpp \
  src/md5.c \
  src/streamables.cpp \
  src/streamers.cpp \
  src/tsprinting.c \
  src/android/gucefCORE_CAndroidSystemLogger.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/android \
  $(MY_MODULE_PATH)/../../common/include \
  $(MY_MODULE_PATH)/../gucefMT/include

LOCAL_CFLAGS := -DGUCEF_CORE_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  gucefMT


LOCAL_LDLIBS := \
  -ldl

include $(BUILD_SHARED_LIBRARY)

