#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := freetype
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/autofit/autofit.c \
  src/base/ftbase.c \
  src/base/ftsystem.c \
  src/base/ftglyph.c \
  src/base/ftbitmap.c \
  src/base/ftinit.c \
  src/bdf/bdf.c \
  src/cache/ftcache.c \
  src/cff/cff.c \
  src/cid/cidriver.c \
  src/cid/cidobjs.c \
  src/cid/cidgload.c \
  src/cid/cidload.c \
  src/cid/cidparse.c \
  src/gxvalid/gxvalid.c \
  src/gzip/ftgzip.c \
  src/lzw/ftlzw.c \
  src/otvalid/otvalid.c \
  src/pcf/pcf.c \
  src/pfr/pfr.c \
  src/psaux/psaux.c \
  src/pshinter/pshinter.c \
  src/psnames/psnames.c \
  src/raster/raster.c \
  src/sfnt/sfnt.c \
  src/smooth/ftsmooth.c \
  src/smooth/ftgrays.c \
  src/truetype/truetype.c \
  src/type1/type1.c \
  src/type42/type42.c \
  src/winfonts/winfnt.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/freetype \
  $(MY_MODULE_PATH)/include/freetype/config \
  $(MY_MODULE_PATH)/include/freetype/internal \
  $(MY_MODULE_PATH)/include/freetype/internal/services \
  $(MY_MODULE_PATH)/src/winfonts

LOCAL_CFLAGS := -DFT2_BUILD_LIBRARY -DFT_CONFIG_OPTION_SYSTEM_ZLIB -DFT_DVEDIT_BUILD_DLL -DFT_DVEDIT_DLL_API


LOCAL_LDLIBS := \
  -lz

include $(BUILD_SHARED_LIBRARY)

