--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: CEGUI.RendererModule.Direct3D9


configuration( { "WIN32" } )
  project( "CEGUI.RendererModule.Direct3D9" )

configuration( { "WIN64" } )
  project( "CEGUI.RendererModule.Direct3D9" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )
  
configuration( { WIN32 } )
links( { "CEGUI", "Direct3D9" } )
  links( { "CEGUI", "d3d9", "d3dx9" } )
  

configuration( { WIN32 } )
defines( { "CEGUIDIRECT3D9RENDERER_EXPORTS" } )
  
configuration( { WIN64 } )
links( { "CEGUI", "Direct3D9" } )
  links( { "CEGUI", "d3d9", "d3dx9" } )
  

configuration( { WIN64 } )
defines( { "CEGUIDIRECT3D9RENDERER_EXPORTS" } )


configuration( { "WIN32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "GeometryBuffer.cpp",
      "Renderer.cpp",
      "Texture.cpp",
      "TextureTarget.cpp",
      "ViewportTarget.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "GeometryBuffer.cpp",
      "Renderer.cpp",
      "Texture.cpp",
      "TextureTarget.cpp",
      "ViewportTarget.cpp"
    } )


configuration( {} )
includedirs( { "../../../include" } )

configuration( { "WIN32" } )
includedirs( { "#$#ENVVAR:DXSDK_DIR#$#/Include", "../../../../../external" } )

configuration( { "WIN64" } )
includedirs( { "#$#ENVVAR:DXSDK_DIR#$#/Include", "../../../../../external" } )
