--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MemoryLeakFinder


configuration( { "LINUX" } )
  project( "MemoryLeakFinder" )

configuration( { "WIN32" } )
  project( "MemoryLeakFinder" )

configuration( { "WIN64" } )
  project( "MemoryLeakFinder" )
location( os.getenv( "PM4OUTPUTDIR" ) )
configuration( { "LINUX" } )
kind( "SharedLib" )
configuration( { "WIN32" } )
kind( "SharedLib" )
configuration( { "WIN64" } )
kind( "SharedLib" )

configuration( { "LINUX" } )
  links( { "gucefCORE", "gucefMT" } )
  links( { "gucefMT" } )
  defines( { "MEMORYLEAKFINDER_BUILD_MODULE" } )

configuration( { "WIN32" } )
  links( { "gucefCORE", "gucefMT" } )
  links( { "gucefMT" } )
  defines( { "MEMORYLEAKFINDER_BUILD_MODULE" } )

configuration( { "WIN64" } )
  links( { "gucefCORE", "gucefMT" } )
  links( { "gucefMT" } )
  defines( { "MEMORYLEAKFINDER_BUILD_MODULE" } )


configuration( { "LINUX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DynMemoryManagerLoader.h",
      "include/gucefMLF_config.h",
      "include/gucefMLF_macros.h",
      "include/gucef_dynnewoff.h",
      "include/gucef_dynnewon.h",
      "include/MemoryManager.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryManager.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DynMemoryManagerLoader.h",
      "include/gucefMLF_config.h",
      "include/gucefMLF_macros.h",
      "include/gucef_dynnewoff.h",
      "include/gucef_dynnewon.h",
      "include/MemoryManager.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryManager.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/DynMemoryManagerLoader.h",
      "include/gucefMLF_config.h",
      "include/gucefMLF_macros.h",
      "include/gucef_dynnewoff.h",
      "include/gucef_dynnewon.h",
      "include/MemoryManager.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryManager.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../gucefCORE/include", "../../gucefMT/include" } )

configuration( { "LINUX" } )
includedirs( { "../../gucefCORE/include/linux", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../gucefCORE/include/mswin", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../gucefCORE/include/mswin", "include" } )
