--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MyGUI.OpenGLPlatform


project( "MyGUI.OpenGLPlatform" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "StaticLib" )

configuration( {} )
links( { "MyGUI.Engine" } )
links( { "MyGUI.Engine" } )
  links( { "GLESv1_CM" } )
  links( { "GL" } )
  links( { "opengl32" } )
  links( { "opengl32" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "../../../Common/FileSystemInfo/FileSystemInfo.h",
  "include/MyGUI_OpenGLDataManager.h",
  "include/MyGUI_OpenGLDiagnostic.h",
  "include/MyGUI_OpenGLImageLoader.h",
  "include/MyGUI_OpenGLPlatform.h",
  "include/MyGUI_OpenGLRenderManager.h",
  "include/MyGUI_OpenGLRTTexture.h",
  "include/MyGUI_OpenGLTexture.h",
  "include/MyGUI_OpenGLVertexBuffer.h",
  "include/GL/glew.h",
  "include/GL/glxew.h",
  "include/GL/wglew.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "include/GL/glew.c",
  "src/MyGUI_OpenGLDataManager.cpp",
  "src/MyGUI_OpenGLPlatform.cpp",
  "src/MyGUI_OpenGLRenderManager.cpp",
  "src/MyGUI_OpenGLRTTexture.cpp",
  "src/MyGUI_OpenGLTexture.cpp",
  "src/MyGUI_OpenGLVertexBuffer.cpp"
 } )


configuration( {} )
includedirs( { "../../../../freetype/include", "../../../../freetype/include/freetype", "../../../../freetype/include/freetype/config", "../../../../freetype/include/freetype/internal", "../../../../freetype/include/freetype/internal/services", "../../../../freetype/src/winfonts", "../../../MyGUIEngine/include", "../../../Common/FileSystemInfo", "include", "include/GL" } )
