#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := gucefINPUT

LOCAL_SRC_FILES := \
  $(LOCAL_PATH)/src/CGUCEFINPUTModule.cpp \
  $(LOCAL_PATH)/src/CInputActionMap.cpp \
  $(LOCAL_PATH)/src/CInputContext.cpp \
  $(LOCAL_PATH)/src/CInputController.cpp \
  $(LOCAL_PATH)/src/CInputDriverPlugin.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CActionEventData.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CInputDriver.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CInputObserverSwitch.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CKeyboard.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CKeyModStateChangedEventData.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CKeyStateChangedEventData.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CMouse.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CMouseButtonEventData.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_CMouseMovedEventData.cpp \
  $(LOCAL_PATH)/src/gucefINPUT_keyboard.cpp

LOCAL_C_INCLUDES := \
  $(LOCAL_PATH)/include \
  $(LOCAL_PATH)/../gucefCORE/include \
  $(LOCAL_PATH)/../gucefMT/include


LOCAL_SHARED_LIBRARIES := \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

