#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := CEGUI.ScriptModule.Lua
LOCAL_MODULE_FILENAME := libCEGUI.ScriptModule.Lua
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  Functor.cpp \
  ScriptModule.cpp \
  lua_CEGUI.cpp \
  required.cpp \
  support/tolua++bin/tolua.c \
  support/tolua++bin/toluabind.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH) \
  $(MY_MODULE_PATH)/support/tolua++bin \
  $(MY_MODULE_PATH)/../../../../../lua/src \
  $(MY_MODULE_PATH)/../../../../../tolua/include \
  $(MY_MODULE_PATH)/../../../../../tolua/src \
  $(MY_MODULE_PATH)/../../../../../tolua/src/lib \
  $(MY_MODULE_PATH)/../../../../../toluapp/include \
  $(MY_MODULE_PATH)/../../../../../toluapp/src \
  $(MY_MODULE_PATH)/../../../../../toluapp/src/lib \
  $(MY_MODULE_PATH)/../../../include \
  $(MY_MODULE_PATH)/support

LOCAL_CFLAGS := -DCEGUILUASCRIPTMODULE_EXPORTS -DLUA_BUILD_AS_DLL


LOCAL_SHARED_LIBRARIES := \
  CEGUI \
  lua \
  tolua


LOCAL_STATIC_LIBRARIES := \
  toluapp

include $(BUILD_SHARED_LIBRARY)

