/*
 *  gucefIMAGE: GUCEF module providing image utilities
 *
 *  Copyright (C) 1998 - 2024.  Dinand Vanvelzen
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#ifndef GUCEF_IMAGE_IMAGETAGS_H
#define GUCEF_IMAGE_IMAGETAGS_H

/*-------------------------------------------------------------------------//
//                                                                         //
//      INCLUDES                                                           //
//                                                                         //
//-------------------------------------------------------------------------*/

#ifndef GUCEF_IMAGE_ETYPES_H
#include "gucefIMAGE_ETypes.h"      /* simple types used */
#define GUCEF_IMAGE_ETYPES_H
#endif /* GUCEF_IMAGE_ETYPES_H ? */

/*-------------------------------------------------------------------------//
//                                                                         //
//      NAMESPACE                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

#ifdef __cplusplus
namespace GUCEF {
namespace IMAGE {
#endif /* __cplusplus ? */

/*-------------------------------------------------------------------------//
//                                                                         //
//      CONSTANTS                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

#define GUCEF_IMAGE_TAG_UNKNOWN						0

/* ----------------------------------------------------------
// EXIF IFD Attribute Information
// --------------------------------------------------------*/

#define GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET    0


/* Tags relating to image data structure */

#define GUCEF_IMAGE_TAG_EXIF_IFD_IMAGE_WIDTH					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0100)
#define GUCEF_IMAGE_TAG_EXIF_IFD_IMAGE_HEIGHT				    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0101)
#define GUCEF_IMAGE_TAG_EXIF_IFD_BITS_PER_SAMPLE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0102)
#define GUCEF_IMAGE_TAG_EXIF_IFD_COMPRESSION					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0103)
#define GUCEF_IMAGE_TAG_EXIF_IFD_PHOTOMETRIC_INTERPRETATION	    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0106)
#define GUCEF_IMAGE_TAG_EXIF_IFD_ORIENTATION					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0112)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SAMPLES_PER_PIXEL			    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0115)
#define GUCEF_IMAGE_TAG_EXIF_IFD_PLANAR_CONFIGURATION		    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x011C)
#define GUCEF_IMAGE_TAG_EXIF_IFD_YCBCR_SUBSAMPLING			    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0212)
#define GUCEF_IMAGE_TAG_EXIF_IFD_YCBCR_POSITIONING			    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0213)
#define GUCEF_IMAGE_TAG_EXIF_IFD_X_RESOLUTION				    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x011A)
#define GUCEF_IMAGE_TAG_EXIF_IFD_Y_RESOLUTION				    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x011B)
#define GUCEF_IMAGE_TAG_EXIF_IFD_RESOLUTION_UNIT				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0128)

/* Tags relating to recording offset */

#define GUCEF_IMAGE_TAG_EXIF_IFD_STRIP_OFFSETS					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0111)
#define GUCEF_IMAGE_TAG_EXIF_IFD_ROWS_PER_STRIP					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0116)
#define GUCEF_IMAGE_TAG_EXIF_IFD_STRIP_BYTE_COUNTS				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0117)
#define GUCEF_IMAGE_TAG_EXIF_IFD_JPEG_INTERCHANGE_FORMAT		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0201)
#define GUCEF_IMAGE_TAG_EXIF_IFD_JPEG_INTERCHANGE_FORMAT_LENGTH	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0202)

/* Other tags */

#define GUCEF_IMAGE_TAG_EXIF_IFD_DATETIME 				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0132)
#define GUCEF_IMAGE_TAG_EXIF_IFD_IMAGE_DESCRIPTION 		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x010E)
#define GUCEF_IMAGE_TAG_EXIF_IFD_MAKE 					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x010F)
#define GUCEF_IMAGE_TAG_EXIF_IFD_MODEL 					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0110)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SOFTWARE 				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0131)
#define GUCEF_IMAGE_TAG_EXIF_IFD_ARTIST 				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x013B)
#define GUCEF_IMAGE_TAG_EXIF_IFD_COPYRIGHT 				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x8298)

/* Tags relating to image data characteristics */

#define GUCEF_IMAGE_TAG_EXIF_IFD_TRANSFER_FUNCTION		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x012D)
#define GUCEF_IMAGE_TAG_EXIF_IFD_WHITE_POINT			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x013E)
#define GUCEF_IMAGE_TAG_EXIF_IFD_PRIMARY_CHROMATICITIES	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x013F)
#define GUCEF_IMAGE_TAG_EXIF_IFD_YCBCR_COEFFICIENTS		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0211)
#define GUCEF_IMAGE_TAG_EXIF_IFD_REFERENCE_BLACK_WHITE	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x0214)

/* Tags relating to version */

#define GUCEF_IMAGE_TAG_EXIF_IFD_VERSION 			        (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9000)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FLASHPIX_VERSION 		    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA000)

/* Tag relating to image data characteristics */

#define GUCEF_IMAGE_TAG_EXIF_IFD_COLOR_SPACE 			    (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA001)

/* Tags relating to image configuration */

#define GUCEF_IMAGE_TAG_EXIF_IFD_COMPONENTS_CONFIGURATION	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9101)
#define GUCEF_IMAGE_TAG_EXIF_IFD_COMPRESSED_BITS_PER_PIXEL	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9102)
#define GUCEF_IMAGE_TAG_EXIF_IFD_PIXEL_X_DIMENSION			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA002)
#define GUCEF_IMAGE_TAG_EXIF_IFD_PIXEL_Y_DIMENSION			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA003)

/* Tags relating to user information */

#define GUCEF_IMAGE_TAG_EXIF_IFD_MARKER_NOTE		        (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x927C)
#define GUCEF_IMAGE_TAG_EXIF_IFD_USER_COMMENT	            (GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9286)
    
/* Tag relating to related file information */

#define GUCEF_IMAGE_TAG_EXIF_IFD_RELATED_SOUND_FILE			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA004)

/* Tags relating to date and time */

#define GUCEF_IMAGE_TAG_EXIF_IFD_DATETIME_ORIGINAL			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9003)
#define GUCEF_IMAGE_TAG_EXIF_IFD_DATETIME_DIGITIZED			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9004)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBSECOND_TIME				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9290)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBSECOND_TIME_ORIGINAL	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9291)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBSECOND_TIME_DIGITIZED	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9292)

/* Tags relating to picture-taking conditions */

#define GUCEF_IMAGE_TAG_EXIF_IFD_EXPOSURE_TIME				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x829A)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FNUMBER					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x829D)
#define GUCEF_IMAGE_TAG_EXIF_IFD_EXPOSURE_PROGRAM			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x8822)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SPECTRAL_SENSITIVITY		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x8824)
#define GUCEF_IMAGE_TAG_EXIF_IFD_ISO_SPEED_RATINGS 			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x8827)
#define GUCEF_IMAGE_TAG_EXIF_IFD_OECF						(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x8828)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SHUTTER_SPEED_VALUE 		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9201)
#define GUCEF_IMAGE_TAG_EXIF_IFD_APERTURE_VALUE 			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9202)
#define GUCEF_IMAGE_TAG_EXIF_IFD_BRIGHTNESS_VALUE			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9203)
#define GUCEF_IMAGE_TAG_EXIF_IFD_EXPOSURE_BIAS_VALUE 		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9204)
#define GUCEF_IMAGE_TAG_EXIF_IFD_MAX_APERTURE_VALUE 		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9205)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBJECT_DISTANCE			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9206)
#define GUCEF_IMAGE_TAG_EXIF_IFD_METERING_MODE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9207)
#define GUCEF_IMAGE_TAG_EXIF_IFD_LIGHT_SOURCE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9208)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FLASH						(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9209)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FOCAL_LENGTH				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x920A)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBJECT_AREA				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0x9214)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FLASH_ENERGY				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA20B)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SPATIAL_FREQ_RESPONSE 		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA20C)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FOCAL_PLANE_X_RES			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA20E)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FOCAL_PLANE_Y_RES			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA20F)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FOCAL_PLANE_UNIT			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA210)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBJECT_LOCATION 			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA214)
#define GUCEF_IMAGE_TAG_EXIF_IFD_EXPOSURE_INDEX				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA215)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SENSING_METHOD				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA217)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FILE_SOURCE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA300)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SCENE_TYPE					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA301)
#define GUCEF_IMAGE_TAG_EXIF_IFD_CFA_PATTERN				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA302)
#define GUCEF_IMAGE_TAG_EXIF_IFD_CUSTOM_RENDERED			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA401)
#define GUCEF_IMAGE_TAG_EXIF_IFD_EXPOSURE_MODE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA402)
#define GUCEF_IMAGE_TAG_EXIF_IFD_WHITE_BALANCE				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA403)
#define GUCEF_IMAGE_TAG_EXIF_IFD_DIGITAL_ZOOM_RATIO			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA404)
#define GUCEF_IMAGE_TAG_EXIF_IFD_FOCAL_LENGTH_IN_35MM_FILM	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA405)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SCENE_CAPTURE_TYPE			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA406)
#define GUCEF_IMAGE_TAG_EXIF_IFD_GAIN_CONTROL				(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA407)
#define GUCEF_IMAGE_TAG_EXIF_IFD_CONTRAST					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA408)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SATURATION					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA409)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SHARPNESS					(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA40A)
#define GUCEF_IMAGE_TAG_EXIF_IFD_DEVICE_SETTING_DESCRIPTION	(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA40B)
#define GUCEF_IMAGE_TAG_EXIF_IFD_SUBJECT_DISTANCE_RANGE		(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA40C)

/* Other tags */

#define GUCEF_IMAGE_TAG_EXIF_IFD_IMAGE_UNIQUE_ID			(GUCEF_IMAGE_TAG_EXIF_IFD_BASE_OFFSET+0xA420)

/* ----------------------------------------------------------
// EXIF GPS Attribute Information
// --------------------------------------------------------*/

#define GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET            0

#define GUCEF_IMAGE_TAG_EXIF_GPS_VERSION_ID				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0000)
#define GUCEF_IMAGE_TAG_EXIF_GPS_LATITUDE_REF			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0001)
#define GUCEF_IMAGE_TAG_EXIF_GPS_LATITUDE				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0002)
#define GUCEF_IMAGE_TAG_EXIF_GPS_LONGITUDE_REF			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0003)
#define GUCEF_IMAGE_TAG_EXIF_GPS_LONGITUDE				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0004)
#define GUCEF_IMAGE_TAG_EXIF_GPS_ALTITUDE_REF			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0005)
#define GUCEF_IMAGE_TAG_EXIF_GPS_ALTITUDE				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0006)
#define GUCEF_IMAGE_TAG_EXIF_GPS_TIME_STAMP				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0007)
#define GUCEF_IMAGE_TAG_EXIF_GPS_SATELLITES				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0008)
#define GUCEF_IMAGE_TAG_EXIF_GPS_STATUS					(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0009)
#define GUCEF_IMAGE_TAG_EXIF_GPS_MEASURE_MODE			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000A)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DOP				    (GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000B)
#define GUCEF_IMAGE_TAG_EXIF_GPS_SPEED_REF				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000C)
#define GUCEF_IMAGE_TAG_EXIF_GPS_SPEED					(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000D)
#define GUCEF_IMAGE_TAG_EXIF_GPS_TRACK_REF				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000E)
#define GUCEF_IMAGE_TAG_EXIF_GPS_TRACK					(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x000F)
#define GUCEF_IMAGE_TAG_EXIF_GPS_IMG_DIRECTION_REF		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0010)
#define GUCEF_IMAGE_TAG_EXIF_GPS_IMG_DIRECTION			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0011)
#define GUCEF_IMAGE_TAG_EXIF_GPS_MAP_DATUM				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0012)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_LATITUDE_REF		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0013)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_LATITUDE			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0014)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_LONGITUDE_REF		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0015)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_LONGITUDE			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0016)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_BEARING_REF		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0017)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_BEARING			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0018)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_DISTANCE_REF		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x0019)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DEST_DISTANCE			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x001A)
#define GUCEF_IMAGE_TAG_EXIF_GPS_PROCESSING_METHOD		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x001B)
#define GUCEF_IMAGE_TAG_EXIF_GPS_AREA_INFORMATION		(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x001C)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DATE_STAMP				(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x001D)
#define GUCEF_IMAGE_TAG_EXIF_GPS_DIFFERENTIAL			(GUCEF_IMAGE_TAG_EXIF_GPS_BASE_OFFSET+0x001E)


/* ==========================================================
// IPTC/NAA tags
// ========================================================*/

#define GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET                100000

#define GUCEF_IMAGE_TAG_IPTC_RECORD_VERSION					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0200)
#define GUCEF_IMAGE_TAG_IPTC_CAPTION						    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0278)
#define GUCEF_IMAGE_TAG_IPTC_WRITER							    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x027A)
#define GUCEF_IMAGE_TAG_IPTC_HEADLINE						    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0269)
#define GUCEF_IMAGE_TAG_IPTC_SPECIAL_INSTRUCTIONS			    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0228)
#define GUCEF_IMAGE_TAG_IPTC_BY_LINE						    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0250)
#define GUCEF_IMAGE_TAG_IPTC_BY_LINE_TITLE					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0255)
#define GUCEF_IMAGE_TAG_IPTC_CREDIT							    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x026E)
#define GUCEF_IMAGE_TAG_IPTC_SOURCE							    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0273)
#define GUCEF_IMAGE_TAG_IPTC_OBJECT_NAME					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0205)
#define GUCEF_IMAGE_TAG_IPTC_DATE_CREATED					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0237)
#define GUCEF_IMAGE_TAG_IPTC_CITY							    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x025A)
#define GUCEF_IMAGE_TAG_IPTC_PROVINCE_OR_STATE				    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x025F)
#define GUCEF_IMAGE_TAG_IPTC_COUNTRY_OR_PRIMARY_LOCATION	    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0265)
#define GUCEF_IMAGE_TAG_IPTC_ORIGINAL_TRANSMISSION_REFERENCE    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0267)
#define GUCEF_IMAGE_TAG_IPTC_CATEGORY						    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x020F)
#define GUCEF_IMAGE_TAG_IPTC_SUPPLEMENTAL_CATEGORIES			(GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0214)
#define GUCEF_IMAGE_TAG_IPTC_URGENCY							(GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x020A)
#define GUCEF_IMAGE_TAG_IPTC_KEYWORDS						    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0219)
#define GUCEF_IMAGE_TAG_IPTC_COPYRIGHT_NOTICE				    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0274)
#define GUCEF_IMAGE_TAG_IPTC_RELEASE_DATE					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x021E)
#define GUCEF_IMAGE_TAG_IPTC_RELEASE_TIME					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0223)
#define GUCEF_IMAGE_TAG_IPTC_TIME_CREATED					    (GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x023C)
#define GUCEF_IMAGE_TAG_IPTC_ORIGINATING_PROGRAM				(GUCEF_IMAGE_TAG_IPTC_BASE_OFFSET+0x0241)

/*-------------------------------------------------------------------------//
//                                                                         //
//      NAMESPACE                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

#ifdef __cplusplus
}; /* namespace IMAGE */
}; /* namespace GUCEF */
#endif /* __cplusplus ? */

/*-------------------------------------------------------------------------*/

#endif /* GUCEF_IMAGE_IMAGETAGS_H ? */
