#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := comcorepluginGEOOSM
LOCAL_MODULE_FILENAME := libcomcorepluginGEOOSM
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/comcorepluginGEOOSM.cpp \
  src/comcorepluginGEOOSM_COsmGeoLocationLookupService.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../../../common/include \
  $(MY_MODULE_PATH)/../../../dependencies/curl/include \
  $(MY_MODULE_PATH)/../../../dependencies/curl/include/curl \
  $(MY_MODULE_PATH)/../../../dependencies/curl/lib \
  $(MY_MODULE_PATH)/../../../dependencies/curl/lib/vauth \
  $(MY_MODULE_PATH)/../../../dependencies/curl/lib/vquic \
  $(MY_MODULE_PATH)/../../../dependencies/curl/lib/vssh \
  $(MY_MODULE_PATH)/../../../dependencies/curl/lib/vtls \
  $(MY_MODULE_PATH)/../../../platform/gucefCOMCORE/include \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include/android \
  $(MY_MODULE_PATH)/../../../platform/gucefMT/include

LOCAL_CFLAGS := -DCOMCOREPLUGIN_GEOOSM_BUILD_PLUGIN_DLL


LOCAL_SHARED_LIBRARIES := \
  curl \
  gucefCOMCORE \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

