#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := gucefIMAGE
LOCAL_MODULE_FILENAME := libgucefIMAGE
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/CGUCEFIMAGEModule.cpp \
  src/gucefIMAGE.cpp \
  src/gucefIMAGE_CCPluginImageCodecItem.cpp \
  src/gucefIMAGE_CGUIImageCodec.cpp \
  src/gucefIMAGE_CIImageCodec.cpp \
  src/gucefIMAGE_CImage.cpp \
  src/gucefIMAGE_CImageCodecPlugin.cpp \
  src/gucefIMAGE_CImageCodecPluginManager.cpp \
  src/gucefIMAGE_CImageCodecRegistry.cpp \
  src/gucefIMAGE_CImageGlobal.cpp \
  src/gucefIMAGE_CIMGCodec.cpp \
  src/gucefIMAGE_CPixelMap.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../common/include \
  $(MY_MODULE_PATH)/../gucefCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include/android \
  $(MY_MODULE_PATH)/../gucefMT/include

LOCAL_CFLAGS := -DGUCEFIMAGE_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  gucefCORE \
  gucefMT

include $(BUILD_SHARED_LIBRARY)

