--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_FilePusher" )

  platforms( { "ALL" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "dependencies/aws-c-common" )
  include( "dependencies/aws-c-event-stream" )
  include( "dependencies/aws-checksums" )
  include( "dependencies/aws-cpp-sdk-core" )
  include( "dependencies/aws-cpp-sdk-s3" )
  include( "dependencies/curl" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libparsifal" )
  include( "dependencies/zlib" )
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "platform/gucefVFS" )
  include( "platform/gucefWEB" )
  include( "plugins/CORE/codecspluginZLIB" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/SHARED/pluginglueAWSSDK" )
  include( "plugins/VFS/vfspluginAWSS3" )
  include( "tools/FilePusher" )
